# Generated by Django 5.2.7 on 2025-11-19 10:33

import django.db.models.deletion
from django.db import migrations, models

import larpmanager.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0105_alter_abilitypx_created_alter_abilitytypepx_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='association',
            field=models.ForeignKey(help_text='The organization this membership belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='larpmanager.association', verbose_name='Association'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='card_number',
            field=models.IntegerField(blank=True, help_text='Unique membership card number assigned by the organization', null=True, verbose_name='Membership card number'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='compiled',
            field=models.BooleanField(default=False, help_text='Indicates whether the member has completed their profile information', verbose_name='Profile completed'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Available credit balance for event payments and purchases', max_digits=10, verbose_name='Credit balance'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date',
            field=models.DateField(blank=True, help_text='Date when the membership was officially approved by the organization', null=True, verbose_name='Membership approval date'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='document',
            field=models.FileField(blank=True, help_text='Upload a photo or scan of your identity document (PDF or image)', null=True, upload_to=larpmanager.models.utils.UploadToPathAndRename('document/'), verbose_name='Identity document'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(help_text='The member associated with this membership', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='larpmanager.member', verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='newsletter',
            field=models.CharField(choices=[('a', 'Yes, keep me posted!'), ('o', 'Only really important communications'), ('n', "No, I don't want updates")], default='a', help_text='Choose how often you want to receive updates about events and activities', max_length=1, verbose_name='Newsletter preferences'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='password_reset',
            field=models.CharField(blank=True, help_text='Temporary token used for password reset process', max_length=100, null=True, verbose_name='Password reset token'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='request',
            field=models.FileField(blank=True, help_text='Upload the signed membership application form (PDF or image)', null=True, upload_to=larpmanager.models.utils.UploadToPathAndRename('request/'), verbose_name='Membership request'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('e', 'Absent'), ('j', 'Shared'), ('u', 'Uploaded'), ('s', 'Submitted'), ('a', 'Accepted'), ('r', 'Kicked out')], db_index=True, default='e', help_text='Current status of the membership application and approval process', max_length=1, verbose_name='Membership status'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='tokens',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Available token balance for event registrations and activities', max_digits=10, verbose_name='Token balance'),
        ),
    ]
