# Generated by Django 5.2.7 on 2025-12-03 10:13

from django.db import migrations, models

import larpmanager.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0108_alter_membership_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='util',
            name='util',
            field=models.FileField(upload_to=larpmanager.models.utils.UploadToPathAndRename('utils/')),
        ),
    ]
