# Generated by Django 5.2.7 on 2025-12-09 18:21

from typing import Any

from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations


def split_token_credit_feature(apps: Any, schema_editor: Any) -> None:
    """Split token_credit feature into separate tokens and credits features.

    For each association that has the token_credit feature active:
    1. Activate both the new tokens and credits features
    2. Migrate old association config keys to new ones
    3. Migrate old event config keys to new ones
    """
    Feature = apps.get_model("larpmanager", "Feature")
    Association = apps.get_model("larpmanager", "Association")
    AssociationConfig = apps.get_model("larpmanager", "AssociationConfig")
    Event = apps.get_model("larpmanager", "Event")
    EventConfig = apps.get_model("larpmanager", "EventConfig")

    # Get the old token_credit feature
    try:
        token_credit_feature = Feature.objects.get(slug="token_credit")
    except ObjectDoesNotExist:
        return

    # Get the new features
    try:
        tokens_feature = Feature.objects.get(slug="tokens")
        credits_feature = Feature.objects.get(slug="credits")
    except ObjectDoesNotExist:
        return

    # Find all associations with token_credit feature active
    associations_with_token_credit = Association.objects.filter(features=token_credit_feature)

    # Activate tokens and credits features and migrate association configs
    for association in associations_with_token_credit:
        association.features.add(tokens_feature)
        association.features.add(credits_feature)

        # Migrate association config: token_credit_token_name -> tokens_name
        old_token_name = AssociationConfig.objects.filter(
            association=association, key="token_credit_token_name"
        ).first()
        if old_token_name and not AssociationConfig.objects.filter(
            association=association, key="tokens_name"
        ).exists():
            AssociationConfig.objects.create(
                association=association, key="tokens_name", value=old_token_name.value
            )

        # Migrate association config: token_credit_credit_name -> credits_name
        old_credit_name = AssociationConfig.objects.filter(
            association=association, key="token_credit_credit_name"
        ).first()
        if old_credit_name and not AssociationConfig.objects.filter(
            association=association, key="credits_name"
        ).exists():
            AssociationConfig.objects.create(
                association=association, key="credits_name", value=old_credit_name.value
            )

        # Migrate event configs for all events in this association
        for event in Event.objects.filter(association=association):
            # Migrate event config: token_credit_disable_t -> tokens_disable
            old_disable_tokens = EventConfig.objects.filter(
                event=event, key="token_credit_disable_t"
            ).first()
            if old_disable_tokens and not EventConfig.objects.filter(
                event=event, key="tokens_disable"
            ).exists():
                EventConfig.objects.create(
                    event=event, key="tokens_disable", value=old_disable_tokens.value
                )

            # Migrate event config: token_credit_disable_c -> credits_disable
            old_disable_credits = EventConfig.objects.filter(
                event=event, key="token_credit_disable_c"
            ).first()
            if old_disable_credits and not EventConfig.objects.filter(
                event=event, key="credits_disable"
            ).exists():
                EventConfig.objects.create(
                    event=event, key="credits_disable", value=old_disable_credits.value
                )


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0110_abilitytemplatepx_and_more'),
    ]

    operations = [
        migrations.RunPython(split_token_credit_feature, reverse_code=migrations.RunPython.noop),
    ]
