# Generated by Django 5.2.7 on 2025-12-17

from typing import Any

from django.db import migrations


def remove_token_credit_feature(apps: Any, schema_editor: Any) -> None:
    """Remove the deprecated token_credit feature."""
    Feature = apps.get_model("larpmanager", "Feature")

    # Delete the token_credit feature if it exists
    # CASCADE will automatically delete associated AssociationPermission and EventPermission
    Feature.objects.filter(slug="token_credit").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0111_split_token_credit_feature'),
    ]

    operations = [
        migrations.RunPython(remove_token_credit_feature, reverse_code=migrations.RunPython.noop),
    ]
