# Generated by Django 5.2.7 on 2025-12-17

from typing import Any

import django.utils.timezone
import model_clone.mixin
from django.db import migrations, models

import larpmanager.models.utils


def migrate_showcase_photos_to_highlights(apps: Any, schema_editor: Any) -> None:
    """Migrate photos from LarpManagerShowcase to LarpManagerHighlight.

    For each existing showcase:
    1. Create a LarpManagerHighlight with the photo and info
    """
    LarpManagerShowcase = apps.get_model("larpmanager", "LarpManagerShowcase")
    LarpManagerHighlight = apps.get_model("larpmanager", "LarpManagerHighlight")

    # Get all showcases (using _base_manager to avoid issues with deleted field)
    showcases = LarpManagerShowcase._base_manager.filter(deleted__isnull=True)

    for showcase in showcases:
        # Skip if no photo data exists
        if not hasattr(showcase, "photo") or not showcase.photo:
            continue

        # Create a new highlight with the showcase's photo and info
        LarpManagerHighlight.objects.create(
            info=getattr(showcase, "info", ""),
            photo=showcase.photo,
        )


def reverse_migration(apps: Any, schema_editor: Any) -> None:
    """Reverse the migration - this is a lossy operation."""
    # Cannot restore data once removed
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0112_remove_token_credit_feature"),
    ]

    operations = [
        # Step 1: Create LarpManagerHighlight model
        migrations.CreateModel(
            name="LarpManagerHighlight",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(db_index=True, editable=False, null=True)),
                ("deleted_by_cascade", models.BooleanField(default=False, editable=False)),
                ("created", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("info", models.CharField(max_length=1000)),
                (
                    "photo",
                    models.ImageField(
                        max_length=500,
                        upload_to=larpmanager.models.utils.UploadToPathAndRename("highlight/"),
                        verbose_name="Photo",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated"],
                "abstract": False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        # Step 2: Migrate data from LarpManagerShowcase to LarpManagerHighlight
        migrations.RunPython(migrate_showcase_photos_to_highlights, reverse_code=reverse_migration),
        # Step 3: Remove fields from LarpManagerShowcase
        migrations.RemoveField(
            model_name="larpmanagershowcase",
            name="info",
        ),
        migrations.RemoveField(
            model_name="larpmanagershowcase",
            name="photo",
        ),
    ]
