# Generated by Django 5.2.7 on 2025-12-18 13:45

from django.db import migrations, models

import larpmanager.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0114_add_member_uuid_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='uuid',
            field=models.CharField(default=larpmanager.models.utils.my_uuid_short, editable=False, help_text='Unique identifier for public profile URLs', max_length=12, unique=True, verbose_name='Public UUID'),
        ),
    ]
