# Generated by Django 5.2.7 on 2025-12-28 18:44

import django.db.models.deletion
from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations, models


def migrate_feature_slug(apps, schema_editor):
    """Migrate feature slug from character_inventory to inventory."""
    Feature = apps.get_model('larpmanager', 'Feature')
    PermissionModule = apps.get_model('larpmanager', 'PermissionModule')

    # Update Feature slug
    Feature.objects.filter(slug='character_inventory').update(slug='inventory')

    # Update PermissionModule slug
    PermissionModule.objects.filter(slug='character_inventory').update(slug='inventory')


def migrate_actor_user_to_member(apps, schema_editor):
    """Migrate actor field from User to Member."""
    InventoryTransfer = apps.get_model('larpmanager', 'InventoryTransfer')
    Member = apps.get_model('larpmanager', 'Member')

    # Get all InventoryTransfer records with an actor
    for transfer in InventoryTransfer.objects.filter(actor_id__isnull=False):
        try:
            # Find the Member associated with this User
            member = Member.objects.get(user_id=transfer.actor_id)
            # Update the actor_id to point to the Member instead of User
            transfer.actor_id = member.id
            transfer.save(update_fields=['actor_id'])
        except ObjectDoesNotExist:
            # If no Member exists for this User, set actor to NULL
            transfer.actor_id = None
            transfer.save(update_fields=['actor_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0116_characterinventory_pooltypeci_inventorytransfer_and_more'),
        ('larpmanager', '0116_larpmanagerblog_larpmanagerguide_keywords_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CharacterInventory',
            new_name='Inventory',
        ),
        # Migrate feature slugs from character_inventory to inventory
        migrations.RunPython(migrate_feature_slug, reverse_code=migrations.RunPython.noop),
        # Migrate actor field data before changing the field type
        migrations.RunPython(migrate_actor_user_to_member, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='inventorytransfer',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='larpmanager.member'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='inventory', to='larpmanager.character'),
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={},
        ),
    ]
