# Generated by Django 5.2.7 on 2026-01-10 09:54

from django.db import migrations, models

import larpmanager.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0122_remove_plotcharacterrel_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='registration_secret',
            field=models.CharField(db_index=True, default=larpmanager.models.utils.my_uuid_short, help_text='This code is used to generate the secret registration link, you may keep the default or customize it', max_length=50, unique=True, verbose_name='Secret code'),
        ),
    ]
