# Generated by Django 5.2.7 on 2026-01-16 23:20

import django.db.models.deletion
import django.utils.timezone
import model_clone.mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0126_fix_event_slug_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('registration_new', 'New Registration'), ('registration_update', 'Updated Registration'), ('registration_cancel', 'Cancelled Registration'), ('payment_money', 'Money Payment'), ('payment_credit', 'Credit Payment'), ('payment_token', 'Token Payment'), ('invoice_approval', 'Invoice Awaiting Approval'), ('help_question', 'Help Question'), ('password_reminder', 'Password Reminder'), ('refund_request', 'Refund Request'), ('invoice_approval_exe', 'Invoice Approval (Executive)')], max_length=30)),
                ('object_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('association', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='larpmanager.association')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='larpmanager.member')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='larpmanager.run')),
            ],
            options={
                'ordering': ['-updated'],
                'abstract': False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
    ]
