# Generated by Django 5.2.7 on 2026-01-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0128_larpmanagertext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtext',
            name='typ',
            field=models.CharField(choices=[('i', 'Character sheet intro'), ('t', 'Terms and conditions'), ('r', 'Registration form'), ('s', 'Search'), ('g', 'Registration mail'), ('a', 'Mail assignment'), ('c', "Player's character form"), ('cs', 'Proposed character'), ('ca', 'Approved character'), ('cr', 'Character review')], max_length=2, verbose_name='Type'),
        ),
    ]
