# Generated by Django 5.2.7 on 2026-01-19 14:10

import django.db.models.deletion
import django.utils.timezone
import model_clone.mixin
from django.db import migrations, models
from django.db.models import Q

import larpmanager.models.utils


def create_email_recipients(apps, schema_editor):
    """Create EmailRecipient for each existing Email (now EmailContent)."""
    EmailContent = apps.get_model("larpmanager", "EmailContent")
    EmailRecipient = apps.get_model("larpmanager", "EmailRecipient")

    # Create EmailRecipient for each EmailContent
    for email_content in EmailContent.objects.all().iterator(chunk_size=500):
        EmailRecipient.objects.create(
            email_content=email_content,
            recipient=email_content.recipient,
            sent=email_content.sent,
            created=email_content.created,
            updated=email_content.updated,
            deleted=email_content.deleted,
        )


def reverse_create_recipients(apps, schema_editor):
    """Delete all EmailRecipients on rollback."""
    EmailRecipient = apps.get_model("larpmanager", "EmailRecipient")
    EmailRecipient.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0129_alter_eventtext_typ'),
    ]

    operations = [
        # Step 1: Rename Email model to EmailContent
        migrations.RenameModel(
            old_name='Email',
            new_name='EmailContent',
        ),

        # Step 2: Rename the database table from larpmanager_email to larpmanager_emailcontent
        migrations.AlterModelTable(
            name='emailcontent',
            table='larpmanager_emailcontent',
        ),

        migrations.AlterModelTable(
            name='emailcontent',
            table=None,
        ),

        # Step 3: Update field verbose names on EmailContent
        migrations.AlterField(
            model_name='emailcontent',
            name='subj',
            field=models.CharField(max_length=500, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='emailcontent',
            name='body',
            field=models.TextField(verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='emailcontent',
            name='reply_to',
            field=models.CharField(blank=True, max_length=170, null=True, verbose_name='Reply To'),
        ),
        migrations.AlterField(
            model_name='emailcontent',
            name='search',
            field=models.CharField(blank=True, max_length=500, verbose_name='Search'),
        ),

        # Step 4: Add indexes to EmailContent
        migrations.AddIndex(
            model_name='emailcontent',
            index=models.Index(condition=Q(deleted__isnull=True), fields=['association'], name='emailcontent_assoc_act'),
        ),
        migrations.AddIndex(
            model_name='emailcontent',
            index=models.Index(condition=Q(deleted__isnull=True), fields=['run'], name='emailcontent_run_act'),
        ),

        # Step 5: Create EmailRecipient model
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uuid', models.CharField(db_index=True, default=larpmanager.models.utils.my_uuid_short, editable=False, max_length=12, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('recipient', models.CharField(max_length=170, verbose_name='Recipient')),
                ('sent', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('language_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Language Code')),
                ('email_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='larpmanager.emailcontent', verbose_name='Email Content')),
            ],
            options={
                'verbose_name': 'Email Recipient',
                'verbose_name_plural': 'Email Recipients',
                'ordering': ['-created'],
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),

        # Step 6: Add indexes to EmailRecipient
        migrations.AddIndex(
            model_name='emailrecipient',
            index=models.Index(condition=Q(deleted__isnull=True), fields=['email_content'], name='emailrecip_content_act'),
        ),
        migrations.AddIndex(
            model_name='emailrecipient',
            index=models.Index(condition=Q(deleted__isnull=True), fields=['sent'], name='emailrecip_sent_act'),
        ),
        migrations.AddIndex(
            model_name='emailrecipient',
            index=models.Index(condition=Q(deleted__isnull=True), fields=['recipient'], name='emailrecip_recip_act'),
        ),

        # Step 7: Migrate data - create EmailRecipient for each EmailContent
        migrations.RunPython(create_email_recipients, reverse_create_recipients),

        # Step 8: Remove unused fields
        migrations.AlterModelOptions(
            name='emailcontent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='emailrecipient',
            options={},
        ),
        migrations.RemoveField(
            model_name='emailcontent',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='emailcontent',
            name='sent',
        ),
        migrations.AlterField(
            model_name='emailrecipient',
            name='uuid',
            field=models.CharField(db_index=True, editable=False, max_length=12, unique=True),
        ),
    ]
