# Generated by Django 5.2.7 on 2026-01-26 15:08

import colorfield.fields
import django.core.validators
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models

import larpmanager.models.utils
import larpmanager.utils.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0130_rename_email_to_emailcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='background',
            field=models.ImageField(blank=True, help_text='Background image displayed across all pages of your organization - use a subtle pattern or texture for best results', max_length=500, upload_to='association_background/', verbose_name='Background image'),
        ),
        migrations.AlterField(
            model_name='association',
            name='font',
            field=models.FileField(blank=True, help_text="Upload a custom font file for page titles to match your organization's branding (TTF, OTF, or WOFF formats)", null=True, upload_to=larpmanager.models.utils.UploadToPathAndRename('association_font/'), validators=[larpmanager.utils.core.validators.FileTypeValidator(['font/ttf', 'font/otf', 'application/font-woff', 'application/font-woff2', 'font/woff', 'font/woff2', 'font/sfnt'])], verbose_name='Custom title font'),
        ),
        migrations.AlterField(
            model_name='association',
            name='main_mail',
            field=models.EmailField(blank=True, help_text='The main email address participants can use to contact your organization', max_length=254, null=True, verbose_name='Contact email'),
        ),
        migrations.AlterField(
            model_name='association',
            name='maintainers',
            field=models.ManyToManyField(blank=True, help_text='Staff members who will receive and manage support tickets', related_name='maintained_associations', to='larpmanager.member', verbose_name='Support maintainers'),
        ),
        migrations.AlterField(
            model_name='association',
            name='name',
            field=models.CharField(help_text='The full name of your organization as it will appear throughout the platform', max_length=100, verbose_name='Organization name'),
        ),
        migrations.AlterField(
            model_name='association',
            name='nationality',
            field=models.CharField(blank=True, choices=[('it', 'Italy')], default='', help_text="Your organization's country (it will enable country-specific features)", max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='association',
            name='payment_currency',
            field=models.CharField(blank=True, choices=[('e', 'EUR'), ('u', 'USD'), ('g', 'GBP'), ('c', 'CAD'), ('j', 'JPY')], default='e', help_text='The currency you want to use for all payments and pricing', max_length=1, null=True, verbose_name='Payment currency'),
        ),
        migrations.AlterField(
            model_name='association',
            name='payment_methods',
            field=models.ManyToManyField(blank=True, help_text='Select which payment methods participants can use', related_name='associations_payments', to='larpmanager.paymentmethod', verbose_name='Payment methods'),
        ),
        migrations.AlterField(
            model_name='association',
            name='pri_rgb',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text="Main color for text content throughout your organization's pages", image_field=None, max_length=25, null=True, samples=None, verbose_name='Text color'),
        ),
        migrations.AlterField(
            model_name='association',
            name='profile',
            field=models.ImageField(blank=True, help_text="Your organization's logo (upload any size, it will be automatically optimized; square images work best)", max_length=500, null=True, upload_to=larpmanager.models.utils.UploadToPathAndRename('association/'), verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='association',
            name='promoter',
            field=models.ImageField(blank=True, help_text="Featured image displayed on the portal's homepage", max_length=500, null=True, upload_to=larpmanager.models.utils.UploadToPathAndRename('promot/'), verbose_name='Promotional image'),
        ),
        migrations.AlterField(
            model_name='association',
            name='sec_rgb',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Color used to highlight important text', image_field=None, max_length=25, null=True, samples=None, verbose_name='Highlight color'),
        ),
        migrations.AlterField(
            model_name='association',
            name='slug',
            field=models.CharField(db_index=True, help_text="Your organization's unique subdomain in the plaftform (Only lowercase letters and numbers allowed, no spaces or special characters)", max_length=20, validators=[django.core.validators.RegexValidator('^[0-9a-z_-]*$', 'Only characters allowed are: 0-9, a-z, _, -.')], verbose_name='Subdomain'),
        ),
        migrations.AlterField(
            model_name='association',
            name='ter_rgb',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Color for clickable links and interactive elements', image_field=None, max_length=25, null=True, samples=None, verbose_name='Link color'),
        ),
        migrations.AlterField(
            model_name='event',
            name='authors',
            field=models.CharField(blank=True, help_text='Names of the people or teams organizing and running this event', max_length=500, null=True, verbose_name='Organizers'),
        ),
        migrations.AlterField(
            model_name='event',
            name='background',
            field=models.ImageField(blank=True, help_text='Background image displayed across all event pages (use a subtle pattern or texture for best results)', max_length=500, upload_to='event_background/', verbose_name='Background image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='carousel_img',
            field=models.ImageField(blank=True, help_text='Optional image for homepage carousel/slideshow (use high-quality wide images for best visual impact)', max_length=500, upload_to='carousel/', verbose_name='Carousel image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='carousel_text',
            field=tinymce.models.HTMLField(blank=True, help_text='Text displayed alongside the carousel image (keep it short and engaging)', max_length=2000, verbose_name='Carousel description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cover',
            field=models.ImageField(blank=True, help_text="Main event image displayed on your organization's homepage (use a rectangular image, ideally 4:3 ratio for best results)", max_length=500, upload_to='cover/', verbose_name='Cover image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='', help_text='Full event description with all important details (will be displayed on the main event page)', max_length=10000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='font',
            field=models.FileField(blank=True, help_text="Upload a custom font file for page titles to match your event's theme (TTF, OTF, or WOFF formats)", null=True, upload_to=larpmanager.models.utils.UploadToPathAndRename('event_font/'), verbose_name='Custom title font'),
        ),
        migrations.AlterField(
            model_name='event',
            name='genre',
            field=models.CharField(blank=True, help_text='The genre or setting of your event', max_length=100, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_filler',
            field=models.IntegerField(default=0, help_text='Maximum number of filler character slots available (set to 0 for unlimited)', verbose_name='Maximum fillers'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_pg',
            field=models.IntegerField(default=0, help_text='Maximum number of participant slots available (set to 0 for unlimited)', verbose_name='Maximum participants'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_waiting',
            field=models.IntegerField(default=0, help_text='Maximum number of people allowed on the waiting list (set to 0 for unlimited)', verbose_name='Maximum waiting list'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='The full name of your event as it will be displayed to participants', max_length=100, verbose_name='Event name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Link this event to another event to create a campaign series where characters are shared (leave empty to start a new campaign)', null=True, on_delete=django.db.models.deletion.CASCADE, to='larpmanager.event', verbose_name='Parent campaign'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pri_rgb',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text="Main color for text content throughout your event's pages", image_field=None, max_length=25, null=True, samples=None, verbose_name='Text color'),
        ),
        migrations.AlterField(
            model_name='event',
            name='register_link',
            field=models.URLField(blank=True, help_text='Link to an external registration system (non-registered users will be redirected here, while registered users get normal access)', max_length=150, verbose_name='External registration link'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sec_rgb',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Color used for text backgrounds and content boxes', image_field=None, max_length=25, null=True, samples=None, verbose_name='Background color'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.CharField(blank=True, db_index=True, help_text='Unique identifier for the event URL (only lowercase letters and numbers allowed, no spaces or special characters)', max_length=30, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-z_-]*$', 'Only characters allowed are: 0-9, a-z, _, -.')], verbose_name='URL identifier'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tagline',
            field=models.CharField(blank=True, help_text='A catchy short phrase or slogan to describe your event', max_length=500, null=True, verbose_name='Tagline'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ter_rgb',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Color for clickable links and interactive elements', image_field=None, max_length=25, null=True, samples=None, verbose_name='Link color'),
        ),
        migrations.AlterField(
            model_name='event',
            name='website',
            field=models.URLField(blank=True, help_text='Link to an external website with additional event information', max_length=100, verbose_name='External website'),
        ),
        migrations.AlterField(
            model_name='event',
            name='where',
            field=models.CharField(blank=True, help_text='Where the event will take place', max_length=500, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='run',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current financial balance for this event', max_digits=10, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='run',
            name='development',
            field=models.CharField(choices=[('0', 'Hidden'), ('1', 'Visible'), ('8', 'Cancelled'), ('9', 'Concluded')], default='0', help_text='Current status of this event', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='run',
            name='end',
            field=models.DateField(blank=True, db_index=True, help_text='The date when this event ends', null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='run',
            name='number',
            field=models.IntegerField(help_text='Sequential number for this event', verbose_name='Run number'),
        ),
        migrations.AlterField(
            model_name='run',
            name='paid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount paid for platform management', max_digits=10, null=True, verbose_name='Amount paid'),
        ),
        migrations.AlterField(
            model_name='run',
            name='plan',
            field=models.CharField(blank=True, choices=[('f', 'Free'), ('p', 'Support')], help_text='The subscription plan associated with this event', max_length=1, null=True, verbose_name='Subscription plan'),
        ),
        migrations.AlterField(
            model_name='run',
            name='registration_open',
            field=models.DateTimeField(blank=True, help_text='Date and time when registrations open for participants (leave blank to keep registrations closed)', null=True, verbose_name='Registration opening'),
        ),
        migrations.AlterField(
            model_name='run',
            name='registration_secret',
            field=models.CharField(db_index=True, default=larpmanager.models.utils.my_uuid_short, help_text='Unique code used to generate the secret registration link (keep the auto-generated value or customize it)', max_length=50, unique=True, verbose_name='Secret registration code'),
        ),
        migrations.AlterField(
            model_name='run',
            name='start',
            field=models.DateField(blank=True, help_text='The date when this event begins', null=True, verbose_name='Start date'),
        ),
    ]
