# Generated by Django 5.2.7 on 2026-01-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0131_alter_association_background_alter_association_font_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Your date of birth', null=True, verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='member',
            name='birth_place',
            field=models.CharField(blank=True, help_text='City and country where you were born', max_length=150, null=True, verbose_name='Birth place'),
        ),
        migrations.AlterField(
            model_name='member',
            name='document_issued',
            field=models.DateField(blank=True, help_text='The date when your identification document was issued', null=True, verbose_name='Date of issue of the document'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(help_text='Your first name as you prefer to be called', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='residence_address',
            field=models.CharField(blank=True, help_text='Your full residential address including street, city, and country', max_length=500, null=True, verbose_name='Residence address'),
        ),
        migrations.AlterField(
            model_name='member',
            name='surname',
            field=models.CharField(help_text='Your last name or family name', max_length=100, verbose_name='Surname'),
        ),
    ]
