# Generated by Django 5.2.7 on 2026-01-29 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0132_alter_member_birth_date_alter_member_birth_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationoption',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Optional - Amount added to the registration fee if selected (0 = no extra cost)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='registrationticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
