# Generated by Django 5.2.7 on 2026-01-30 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0133_alter_registrationoption_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_filler',
            field=models.IntegerField(default=0, help_text='Maximum number of filler character slots available (set to 0 for unlimited)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum fillers'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_pg',
            field=models.IntegerField(default=0, help_text='Maximum number of participant slots available (set to 0 for unlimited)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum participants'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_waiting',
            field=models.IntegerField(default=0, help_text='Maximum number of people allowed on the waiting list (set to 0 for unlimited)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum waiting list'),
        ),
        migrations.AlterField(
            model_name='registrationoption',
            name='max_available',
            field=models.IntegerField(default=0, help_text='Optional - Maximum number of times it can be selected across all registrations (0 = unlimited)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum number'),
        ),
        migrations.AlterField(
            model_name='registrationticket',
            name='max_available',
            field=models.IntegerField(default=0, help_text='Optional - Maximum number of times it can be requested across all signups (0 = unlimited)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='writingoption',
            name='max_available',
            field=models.IntegerField(default=0, help_text='Optional - Maximum number of times it can be selected across all characters (0 = unlimited)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
