# Generated by Django 5.2.7 on 2026-02-04 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0134_alter_event_max_filler_alter_event_max_pg_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={},
        ),
        migrations.RemoveField(
            model_name='log',
            name='dl',
        ),
        migrations.AddField(
            model_name='log',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='larpmanager.association'),
        ),
        migrations.AddField(
            model_name='log',
            name='element_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='log',
            name='info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='operation_type',
            field=models.CharField(choices=[('new', 'New'), ('update', 'Update'), ('delete', 'Delete'), ('bulk', 'Bulk operation'), ('upload', 'Upload')], db_index=True, default='update', max_length=10),
        ),
        migrations.AddField(
            model_name='log',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='larpmanager.run'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['member', '-created'], name='larpmanager_member__45b31c_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['-created'], name='larpmanager_created_872ece_idx'),
        ),
    ]
