# Generated by Claude Code 2026-02-08
# Performance optimization indexes for common query patterns

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0136_add_registration_status'),
    ]

    operations = [
        # Index for cancellation queries - partial index on non-null values
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(
                fields=['cancellation_date'],
                name='reg_cancel_date_idx',
                condition=models.Q(cancellation_date__isnull=False),
            ),
        ),
        # Index for refund queries - partial index on refunded registrations
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(
                fields=['refunded'],
                name='reg_refunded_idx',
                condition=models.Q(refunded=True),
            ),
        ),
        # Composite index for run + cancellation queries
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(
                fields=['run', 'cancellation_date'],
                name='reg_run_cancel_idx',
            ),
        ),
        # Composite index for payment invoice status + created date queries
        migrations.AddIndex(
            model_name='paymentinvoice',
            index=models.Index(
                fields=['status', 'created'],
                name='payinv_status_created_idx',
            ),
        ),
        # Index for member email lookups
        migrations.AddIndex(
            model_name='member',
            index=models.Index(
                fields=['email'],
                name='member_email_idx',
            ),
        ),
    ]
