# Generated by Django 5.2.7 on 2026-02-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0139_add_membership_performance_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writinganswer',
            name='element_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='writingchoice',
            name='element_id',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='registrationanswer',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('registration', 'question'), name='unique_registration_answer'),
        ),
        migrations.AddConstraint(
            model_name='registrationchoice',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('registration', 'option'), name='unique_registration_choice'),
        ),
        migrations.AddConstraint(
            model_name='writinganswer',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('element_id', 'question'), name='unique_writing_answer'),
        ),
        migrations.AddConstraint(
            model_name='writingchoice',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('element_id', 'option'), name='unique_writing_choice'),
        ),
    ]
