# Generated by Django 5.2.7 on 2026-02-17 14:10

import django.core.validators
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0140_alter_writinganswer_element_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='additionals',
            field=models.IntegerField(default=0, help_text='Number of additional participants', verbose_name='Additionals'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='multi_registrations', through='larpmanager.RegistrationCharacterRel', to='larpmanager.character', verbose_name='Characters'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='pay_what',
            field=models.IntegerField(default=0, help_text='Donation amount chosen by the participant', verbose_name='Donation'),
        ),
        migrations.AlterField(
            model_name='registrationinstallment',
            name='amount',
            field=models.IntegerField(help_text='Total amount of payment to be received by this date (0 = all outstanding)', verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='registrationinstallment',
            name='date_deadline',
            field=models.DateField(blank=True, help_text='Deadline date', null=True, verbose_name='Date deadline'),
        ),
        migrations.AlterField(
            model_name='registrationinstallment',
            name='days_deadline',
            field=models.IntegerField(blank=True, help_text='Deadline in the measure of days from enrollment (fill in one between the fixed deadline and the deadline in days)', null=True, verbose_name='Days deadline'),
        ),
        migrations.AlterField(
            model_name='registrationinstallment',
            name='tickets',
            field=models.ManyToManyField(blank=True, help_text='Indicate the tickets for which it is active', related_name='installments', to='larpmanager.registrationticket', verbose_name='Tickets'),
        ),
        migrations.AlterField(
            model_name='registrationquota',
            name='days_available',
            field=models.IntegerField(help_text='Minimum number of days before the event for which it is made available (0  = always)', verbose_name='Days available'),
        ),
        migrations.AlterField(
            model_name='registrationquota',
            name='quotas',
            field=models.IntegerField(help_text='Quotas total number', verbose_name='Quotas'),
        ),
        migrations.AlterField(
            model_name='registrationquota',
            name='surcharge',
            field=models.IntegerField(default=0, help_text='Extra price applied when this quota is active', verbose_name='Surcharge'),
        ),
        migrations.AlterField(
            model_name='registrationsection',
            name='description',
            field=tinymce.models.HTMLField(blank=True, help_text='Description - will be displayed at the beginning of the section', max_length=5000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='registrationsection',
            name='name',
            field=models.CharField(help_text='Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='registrationsurcharge',
            name='amount',
            field=models.IntegerField(help_text='Surcharge applied to the ticket', verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='registrationsurcharge',
            name='date',
            field=models.DateField(help_text='Date from when the surcharge is applied', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='registrationticket',
            name='casting_priority',
            field=models.IntegerField(default=1, help_text='Optional - Casting priority granted by this option (e.g., 1 = low, 5 = medium, 25 = high)', verbose_name='Casting priority'),
        ),
        migrations.AlterField(
            model_name='registrationticket',
            name='giftable',
            field=models.BooleanField(default=False, help_text='Optional - Indicates whether the ticket can be gifted to other participants', verbose_name='Giftable'),
        ),
        migrations.AlterField(
            model_name='registrationticket',
            name='max_available',
            field=models.IntegerField(default=0, help_text='Optional - Maximum number of times it can be requested across all signups (0 = unlimited)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total availability'),
        ),
        migrations.AlterField(
            model_name='registrationticket',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='registrationticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ticket price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='registrationticket',
            name='tier',
            field=models.CharField(choices=[('b', 'Standard'), ('y', 'New player'), ('l', 'Lottery'), ('w', 'Waiting'), ('f', 'Filler'), ('r', 'Reduced'), ('p', 'Patron'), ('t', 'Staff'), ('n', 'NPC'), ('c', 'Collaborator'), ('s', 'Seller')], default='b', help_text='Type of ticket', max_length=1, verbose_name='Tier'),
        ),
        migrations.AlterField(
            model_name='registrationticket',
            name='visible',
            field=models.BooleanField(default=True, help_text='Is it selectable by participants?', verbose_name='Visible'),
        ),
    ]
