# Generated by Django 5.2.7 on 2026-02-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0141_alter_registration_additionals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='demo',
            field=models.BooleanField(default=True),
        ),
    ]
