# Generated by Django 5.2.7 on 2026-03-12 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0145_set_initial_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilitypx',
            name='requirements',
            field=models.ManyToManyField(blank=True, help_text='Indicate the character options, which must be selected to make the ability available', related_name='abilities', to='larpmanager.writingoption', verbose_name='Requirements'),
        ),
        migrations.AlterField(
            model_name='association',
            name='slug',
            field=models.CharField(db_index=True, help_text="Your organization's unique subdomain in the platform (Only lowercase letters and numbers allowed, no spaces or special characters)", max_length=20, validators=[django.core.validators.RegexValidator('^[0-9a-z_-]*$', 'Only characters allowed are: 0-9, a-z, _, -.')], verbose_name='Subdomain'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='descr',
            field=models.CharField(help_text='A description of the abilities involved', max_length=5000),
        ),
    ]
