# Generated by Django 5.2.7 on 2026-03-17 21:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0146_alter_abilitypx_requirements_alter_association_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Indicate the value of the discount, it will be deducted from the total amount calculated', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
