# Generated by Django 5.2.7 on 2026-03-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0149_writingquestion_editable_default_all_statuses'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(condition=models.Q(('cancellation_date__isnull', True), ('deleted', None), ('redeem_code__isnull', True)), fields=('run', 'member'), name='unique_active_registration_per_run_member'),
        ),
    ]
