# Generated by Django 5.2.7 on 2026-03-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0150_unique_active_registration_per_run_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faction',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='writingquestion',
            name='typ',
            field=models.CharField(choices=[('s', 'Single choice'), ('m', 'Multiple choice'), ('t', 'Single-line text'), ('p', 'Multi-line text'), ('e', 'Advanced text editor'), ('name', 'Name'), ('teaser', 'Presentation'), ('text', 'Sheet'), ('cover', 'Cover'), ('faction', 'Factions'), ('title', 'Title'), ('mirror', 'Mirror'), ('hide', 'Hide'), ('locked', 'Locked'), ('progress', 'Progress'), ('assigned', 'Assigned'), ('c', 'Computed')], default='s', help_text='Question type', max_length=10, verbose_name='Type'),
        ),
    ]
