# Generated by Django 5.2.7 on 2026-03-31 21:32

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0151_character_locked_faction_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='log',
            name='operation_type',
            field=models.CharField(choices=[('new', 'New'), ('update', 'Update'), ('delete', 'Delete'), ('bulk', 'Bulk operation'), ('upload', 'Upload'), ('restore', 'Restore')], db_index=True, default='update', max_length=10),
        ),
    ]
