# Generated by Django 5.2.7 on 2026-04-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0152_faction_color_alter_log_operation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemexp',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Hidden'),
        ),
    ]
