# Generated by Django 5.2.7 on 2026-05-01 12:28

import django.utils.timezone
import model_clone.mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0155_interface_version_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='LarpManagerNewsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('a', 'Active'), ('n', 'Non active'), ('u', 'Unsubscribed')], default='n', max_length=1)),
            ],
            options={
                'ordering': ['-updated'],
                'abstract': False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default=None, help_text='Indicate your legal gender as it appears on official documents. It will only be used for internal bureaucratic purposes, and will NEVER be displayed to other participants. ', max_length=1, null=True, verbose_name='Legal Gender'),
        ),
        migrations.AlterField(
            model_name='member',
            name='legal_name',
            field=models.CharField(blank=True, help_text='If for whatever reason the first and last name shown on your documents is different from the one you prefer to use, then write it here. It will only be used for internal bureaucratic purposes, and will NEVER be displayed to other participants. ', max_length=100, null=True, verbose_name='Legal name'),
        ),
    ]
