# Generated by Django 5.2.7 on 2026-04-30 10:57

import django.utils.timezone
import model_clone.mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0156_larpmanagernewsletter_alter_member_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('value', models.CharField(max_length=1000)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='larpmanager_name_cd5d82_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'deleted'), name='unique_config_with_optional'), models.UniqueConstraint(condition=models.Q(('deleted', None)), fields=('name',), name='unique_config_without_optional')],
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='event',
            name='genre',
            field=models.CharField(blank=True, help_text='The genre of your event', max_length=100,
                                   verbose_name='Genre'),
        ),
    ]
