# Generated by Django 5.2.7 on 2026-05-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0157_alter_member_gender_alter_member_legal_name_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='larpmanagerguide',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
