# Generated by Django 5.2.7 on 2026-05-11 13:55

import django.utils.timezone
import larpmanager.models.utils
import model_clone.mixin
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0159_eventbutton_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='LarpManagerPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('profile', models.ImageField(blank=True, max_length=500, null=True, upload_to=larpmanager.models.utils.UploadToPathAndRename('partners/'), verbose_name='Profile Image')),
            ],
            options={
                'ordering': ['-updated'],
                'abstract': False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='larpmanagertext',
            name='value',
            field=tinymce.models.HTMLField(verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='member',
            name='legal_name',
            field=models.CharField(blank=True, help_text='If the first name shown on your documents is different from the one you prefer to use, then write it here; otherwise leave this field empty. It will only be used for internal bureaucratic purposes, and will NEVER be displayed to other participants. ', max_length=100, null=True, verbose_name='Legal name'),
        ),
        migrations.AlterField(
            model_name='larpmanagertext',
            name='value',
            field=tinymce.models.HTMLField(verbose_name='Value'),
        ),
    ]
