# Generated by Django 5.2.7 on 2026-05-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0161_membership_fee_separated_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcontent',
            name='attachment_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Attachment Path'),
        ),
        migrations.AlterField(
            model_name='larpmanagertext',
            name='value',
            field=models.TextField(verbose_name='Value'),
        ),
    ]
