# Generated by Django 5.2.7 on 2026-05-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0162_add_emailcontent_attachment_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcontent',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Attachment Name'),
        ),
    ]
