# Generated by Django 5.2.7 on 2026-05-21 15:47

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0164_remove_player_cancellation_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='text',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
