# Generated by Django 5.2.7 on 2026-05-27 08:40

import django.db.models.deletion
import django.utils.timezone
import model_clone.mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0165_relationship_auto_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, editable=False, max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_invites', to='larpmanager.association')),
                ('association_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='larpmanager.associationrole')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_invites', to='larpmanager.event')),
                ('event_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='larpmanager.eventrole')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_role_invites', to='larpmanager.member')),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_role_invites', to='larpmanager.member')),
            ],
            options={
                'ordering': ['-updated'],
                'abstract': False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='associationrole',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='association_roles', to='larpmanager.member'),
        ),
        migrations.AlterField(
            model_name='eventrole',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='event_roles', to='larpmanager.member'),
        ),
    ]
