# Generated by Django 5.2.7 on 2026-05-30 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0166_roleinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilityexp',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='larpmanager.systemexp', verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='deliveryexp',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='larpmanager.systemexp', verbose_name='System'),
        ),
    ]
