# Generated by Django 5.2.7 on 2026-06-20 12:31

from typing import Any

from django.db import migrations, models


def set_initial_order(apps: Any, schema_editor: Any) -> None:
    """Set order = number * 10 for writing models that newly got the order field."""
    model_names = ["Character", "Handout", "Prologue", "PrologueType", "Quest", "QuestType", "SpeedLarp", "Trait", "SystemExp", "AbilityExp", "AbilityTypeExp", "AbilityTemplateExp", "DeliveryExp",
        "EventButton", "Discount", "WorkshopModule", "WorkshopQuestion", "WorkshopOption"]
    for model_name in model_names:
        Model = apps.get_model("larpmanager", model_name)
        instances = list(Model.objects.all())
        for instance in instances:
            instance.order = instance.number * 10
        Model.objects.bulk_update(instances, ["order"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0168_add_media_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuremodule',
            options={},
        ),
        migrations.AlterModelOptions(
            name='larpmanagerdiscover',
            options={},
        ),
        migrations.AlterModelOptions(
            name='larpmanagerfaqtype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='larpmanagertutorial',
            options={},
        ),
        migrations.AlterModelOptions(
            name='permissionmodule',
            options={},
        ),
        migrations.AddField(
            model_name='character',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='handout',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prologue',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prologuetype',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quest',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questtype',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='speedlarp',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trait',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="systemexp",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="abilityexp",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="abilitytypeexp",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="abilitytemplateexp",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="deliveryexp",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="eventbutton",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="discount",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="workshopmodule",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="workshopquestion",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="workshopoption",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(set_initial_order, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='feature',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='featuremodule',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='larpmanagerdiscover',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='larpmanagerfaqtype',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='larpmanagertutorial',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='modifierexp',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='permissionmodule',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registrationinstallment',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registrationticket',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
