# Generated by Django 5.2.7 on 2026-06-07 17:46

import django.db.models.deletion
import django.utils.timezone
import model_clone.mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0168_add_media_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PoolBalanceCI',
            new_name='PoolBalance',
        ),
        migrations.CreateModel(
            name='InventoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uuid', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('restrict_pools', models.BooleanField(default=False, help_text='If enabled, only pool types belonging to the selected labels will appear in inventories of this type.')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='larpmanager.event')),
            ],
            options={
                'ordering': ['event', 'number'],
                'abstract': False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.AddField(
            model_name='inventory',
            name='inventory_type',
            field=models.ForeignKey(blank=True, help_text='Optional type that controls which pool types are available. If unset, all pool types are shown (backward compatible).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', to='larpmanager.inventorytype'),
        ),
        migrations.RenameModel(
            old_name='PoolTypeCI',
            new_name='PoolType',
        ),
        migrations.CreateModel(
            name='PoolLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uuid', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='larpmanager.event')),
                ('pool_types', models.ManyToManyField(blank=True, help_text='Pool types that belong to this label.', related_name='labels', to='larpmanager.pooltype')),
            ],
            options={
                'ordering': ['event', 'number'],
                'abstract': False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.AddField(
            model_name='inventorytype',
            name='labels',
            field=models.ManyToManyField(blank=True, help_text='Labels whose pool types are available to inventories of this type (only used when restrict_pools is enabled).', related_name='inventory_types', to='larpmanager.poollabel'),
        ),
    ]
