# Generated by Django 5.2.7 on 2026-06-24 14:15

import django.db.models.deletion
import django.utils.timezone
import model_clone.mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0169_alter_featuremodule_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterionExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uuid', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('order', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('operation', models.CharField(choices=[('ADD', 'Addition'), ('SUB', 'Subtraction'), ('MUL', 'Multiplication'), ('DIV', 'Division')], default='ADD', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='larpmanager.event')),
                ('prerequisites', models.ManyToManyField(blank=True, help_text='All prerequisite abilities must be owned for this criterion to apply', related_name='criterion_prerequisites', to='larpmanager.abilityexp', verbose_name='Pre-requisites')),
                ('requirements', models.ManyToManyField(blank=True, help_text='All required character options must be selected for this criterion to apply', related_name='criterion_requirements', to='larpmanager.writingoption', verbose_name='Requirements')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterions', to='larpmanager.systemexp', verbose_name='System')),
            ],
            options={
                'indexes': [models.Index(fields=['number', 'event'], name='larpmanager_number_c63d14_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'number', 'deleted'), name='unique_criterion_with_optional'), models.UniqueConstraint(condition=models.Q(('deleted', None)), fields=('event', 'number'), name='unique_criterion_without_optional')],
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
    ]
