# Generated by Django 5.2.7 on 2026-06-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0170_criterionexp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterionexp',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='This criterion will apply only to characters owning all prerequisite abilities', related_name='criterion_prerequisites', to='larpmanager.abilityexp', verbose_name='Pre-requisites'),
        ),
        migrations.AlterField(
            model_name='criterionexp',
            name='requirements',
            field=models.ManyToManyField(blank=True, help_text='This criterion will apply only to characters with all required options', related_name='criterion_requirements', to='larpmanager.writingoption', verbose_name='Requirements'),
        ),
    ]
