# Generated by Django 5.2.7 on 2026-07-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0169_rename_poolbalanceci_poolbalance_inventorytype_and_more'),
        ('larpmanager', '0171_alter_criterionexp_prerequisites_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorytype',
            name='restrict_pools',
        ),
        migrations.AlterField(
            model_name='inventorytype',
            name='labels',
            field=models.ManyToManyField(blank=True, help_text='Labels whose pool types are available to inventories of this type. If empty, all pool types are shown.', related_name='inventory_types', to='larpmanager.poollabel'),
        ),
        migrations.AlterField(
            model_name='run',
            name='registration_open',
            field=models.DateTimeField(blank=True, help_text='Date and time when registrations open, or close, for participants depending on status', null=True, verbose_name='Registration date'),
        ),
        migrations.AlterField(
            model_name='run',
            name='registration_status',
            field=models.CharField(choices=[('p', 'Pre-registration'), ('c', 'Closed'), ('o', 'Open'), ('e', 'External site'), ('f', 'Open on date'), ('g', 'Close on date')], default='c', help_text='Registrations status for this event', max_length=1, verbose_name='Registrations status'),
        ),
    ]
