# Generated by Django 5.2.7 on 2026-07-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0172_merge_20260702_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterionexp',
            name='factions',
            field=models.ManyToManyField(blank=True, help_text='If you select one (or more) factions, this criterion applies only to characters belonging to all of them', related_name='criterions_exp', to='larpmanager.faction', verbose_name='Faction list'),
        ),
        migrations.AddField(
            model_name='modifierexp',
            name='factions',
            field=models.ManyToManyField(blank=True, help_text='If you select one (or more) factions, this modifier applies only to characters belonging to all of them', related_name='modifiers_exp', to='larpmanager.faction', verbose_name='Faction list'),
        ),
        migrations.AlterField(
            model_name='criterionexp',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='If you select one (or more) abilities, this criterion applies only to characters with all of them', related_name='criterion_prerequisites', to='larpmanager.abilityexp', verbose_name='Pre-requisites'),
        ),
        migrations.AlterField(
            model_name='criterionexp',
            name='requirements',
            field=models.ManyToManyField(blank=True, help_text='If you select one (or more) character options, this criterion applies only to characters with all of them', related_name='criterion_requirements', to='larpmanager.writingoption', verbose_name='Requirements'),
        ),
        migrations.AlterField(
            model_name='modifierexp',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='If you select one (or more) character abilities, this modifier applies only to characters with all of them', related_name='modifiers_prerequisites', to='larpmanager.abilityexp', verbose_name='Pre-requisites'),
        ),
        migrations.AlterField(
            model_name='modifierexp',
            name='requirements',
            field=models.ManyToManyField(blank=True, help_text='If you select one (or more) character options, this modifier applies only to characters with all of them', related_name='modifiers_requirements', to='larpmanager.writingoption', verbose_name='Requirements'),
        ),
    ]
