# Generated by Django 5.2.7 on 2026-07-12 17:37

import django.db.models.deletion
import django.utils.timezone
import larpmanager.models.utils
import model_clone.mixin
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0173_criterionexp_factions_modifierexp_factions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uuid', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('media_token', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('order', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('teaser', tinymce.models.HTMLField(blank=True, help_text="Presentation visible to all participants, when 'show presentation' is checked", max_length=100000, verbose_name='Presentation')),
                ('text', tinymce.models.HTMLField(blank=True, help_text="Text visible only by the assigned participant, when 'show text' is checked", max_length=100000)),
                ('temp', models.BooleanField(default=False)),
                ('hide', models.BooleanField(default=False)),
                ('cover', models.ImageField(blank=True, help_text='Guild logo', max_length=500, null=True, upload_to=larpmanager.models.utils.UploadToPathAndRename('guild/cover/'), verbose_name='Guild cover')),
                ('assigned', models.ForeignKey(blank=True, help_text='Assigned staff member', null=True, on_delete=django.db.models.deletion.SET_NULL, to='larpmanager.member')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='larpmanager.event')),
                ('progress', models.ForeignKey(blank=True, help_text='Progress status', null=True, on_delete=django.db.models.deletion.SET_NULL, to='larpmanager.progressstep')),
            ],
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GuildMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('a', 'Admin'), ('m', 'Member')], default='m', max_length=1, verbose_name='Role')),
                ('status', models.CharField(choices=[('i', 'Invited'), ('a', 'Accepted')], default='i', max_length=1, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guild_memberships', to='larpmanager.character')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='larpmanager.guild')),
            ],
        ),
        migrations.AddField(
            model_name='guild',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='guilds_list', through='larpmanager.GuildMembership', to='larpmanager.character'),
        ),
        migrations.AddConstraint(
            model_name='guildmembership',
            constraint=models.UniqueConstraint(fields=('guild', 'character'), name='unique_guild_character'),
        ),
        migrations.AddIndex(
            model_name='guild',
            index=models.Index(fields=['number', 'event', 'order'], name='larpmanager_number_6a4f6b_idx'),
        ),
        migrations.AddIndex(
            model_name='guild',
            index=models.Index(condition=models.Q(('deleted__isnull', True)), fields=['event'], name='gui_evt_act'),
        ),
        migrations.AlterField(
            model_name='textversion',
            name='tp',
            field=models.CharField(
                choices=[('p', 'Plot'), ('c', 'Character'), ('h', 'Faction'), ('u', 'Guild'), ('q', 'Quest'),
                         ('t', 'Trait'), ('a', 'Article'), ('o', 'Handout'), ('g', 'Prologue'), ('e', 'QuestType'),
                         ('s', 'SpeedLarp'), ('r', 'PlotCharacter'), ('l', 'Relationship')], max_length=1),
        ),
        migrations.AlterField(
            model_name='writingquestion',
            name='applicable',
            field=models.CharField(
                choices=[('c', 'character'), ('p', 'plot'), ('f', 'faction'), ('q', 'quest'), ('t', 'trait'),
                         ('r', 'prologue'), ('g', 'guild')], default='c',
                help_text='Select the types of writing elements that this question applies to', max_length=1,
                verbose_name='Applicable'),
        ),
    ]
