# Generated by Django 5.2.7 on 2026-07-10
import django
from django.db import migrations, models
import colorfield.fields

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_clone.mixin
import tinymce.models

def clear_association_caches(apps, schema_editor):
    """Clear cached association dicts so they are rebuilt with the new demo key."""
    from larpmanager.cache.association import clear_association_cache

    Association = apps.get_model('larpmanager', 'Association')
    for slug in Association.objects.values_list('slug', flat=True):
        clear_association_cache(slug)


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0174_add_guild'),
    ]

    operations = [
        migrations.RenameField(
            model_name='association',
            old_name='demo',
            new_name='lite_mode',
        ),
        migrations.CreateModel(
            name='LarpManagerDemoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uuid', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('order', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True, validators=[
                    django.core.validators.RegexValidator('^[0-9a-z_-]*$',
                                                          'Only characters allowed are: 0-9, a-z, _, -.')])),
                ('icon',
                 models.CharField(blank=True, help_text='FontAwesome icon class shown on the button', max_length=50)),
                ('descr', models.CharField(blank=True, max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('template_association',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demo_types',
                                   to='larpmanager.association')),
            ],
            options={
                'abstract': False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LarpManagerDemoHint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uuid', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('order', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('view_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=200)),
                ('content', tinymce.models.HTMLField()),
                ('active', models.BooleanField(default=True)),
                ('demo_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                related_name='hints', to='larpmanager.larpmanagerdemotype')),
            ],
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.AddField(
            model_name='association',
            name='demo_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='instances', to='larpmanager.larpmanagerdemotype'),
        ),
        migrations.CreateModel(
            name='LarpManagerDemoHintDismissal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissals',
                                           to='larpmanager.larpmanagerdemohint')),
                ('member',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_hint_dismissals',
                                   to='larpmanager.member')),
            ],
            options={
                'unique_together': {('member', 'hint')},
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='larpmanagerdemohint',
            index=models.Index(fields=['view_name', 'active'], name='larpmanager_view_na_1a09d9_idx'),
        ),
        migrations.AddField(
            model_name='larpmanagerdemotype',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None,
                                               help_text='Accent color shown on the demo card in the get started page',
                                               image_field=None, max_length=25, null=True, samples=None,
                                               verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='larpmanagerdemotype',
            name='allowed_config',
            field=models.TextField(blank=True, help_text='Comma separated list of config section slugs allowed to be shown (and auto-opened) in the association/event configuration forms for this demo type. Empty means no restriction.'),
        ),
        migrations.AddField(
            model_name='larpmanagerdemotype',
            name='allowed_sidebar',
            field=models.TextField(blank=True, help_text='Comma separated list of event/association permission slugs allowed in the sidebar for this demo type. Empty means no restriction.'),
        ),
        migrations.AddField(
            model_name='larpmanagerdemotype',
            name='is_campaign',
            field=models.BooleanField(default=False, help_text='Template association has multiple events under one campaign: grant the demo user an association-wide role and land on the association dashboard, instead of organizer of the first event.'),
        ),
        migrations.RunPython(clear_association_caches, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='association',
            name='slug',
            field=models.CharField(db_index=True,
                                   help_text="Your organization's unique subdomain in the platform (Only lowercase letters and numbers allowed, no spaces or special characters)",
                                   max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-z_-]*$',
                                                                                                    'Only characters allowed are: 0-9, a-z, _, -.')],
                                   verbose_name='Subdomain'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.CharField(blank=True, db_index=True,
                                   help_text='Unique identifier for the event URL (only lowercase letters and numbers allowed, no spaces or special characters)',
                                   max_length=50, null=True, validators=[
                    django.core.validators.RegexValidator('^[0-9a-z_-]*$',
                                                          'Only characters allowed are: 0-9, a-z, _, -.')],
                                   verbose_name='URL identifier'),
        ),
    ]
