# Generated by Django 5.2.7 on 2026-07-16 13:36

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0176_alter_refundrequest_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='accountingitemdiscount',
            name='run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='larpmanager.run', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='accountingitemexpense',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='larpmanager.run', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='accountingiteminflow',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='larpmanager.run', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='accountingitemother',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='larpmanager.run', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='accountingitemoutflow',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='larpmanager.run', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections_runs', to='larpmanager.run', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='larpmanagerdemotype',
            name='allowed_sidebar',
            field=models.TextField(blank=True, help_text='Comma separated list of event/association permission slugs allowed in the sidebar, and feature slugs allowed in the player-facing navigation, for this demo type. Empty means no restriction.'),
        ),
        migrations.AlterField(
            model_name='recordaccounting',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rec_accs', to='larpmanager.run', verbose_name='Event'),
        ),
    ]
