# Generated by Django 5.2.7 on 2026-07-17 01:17

import django.utils.timezone
import larpmanager.models.utils
import model_clone.mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0177_guild_color_alter_accountingitemdiscount_run_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LarpManagerScreenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('order', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(max_length=1000)),
                ('photo', models.ImageField(max_length=500, upload_to=larpmanager.models.utils.UploadToPathAndRename('screenshot/'), verbose_name='Photo')),
            ],
            options={
                'abstract': False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
    ]
