# Generated by Django 5.2.7 on 2026-07-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0180_larpmanagercollaborator'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationquestion',
            name='applicable',
            field=models.CharField(choices=[('r', 'registration'), ('m', 'matchmaker')], default='r', help_text='Select which form this question belongs to', max_length=1, verbose_name='Applicable'),
        ),
        migrations.AddIndex(
            model_name='registrationquestion',
            index=models.Index(condition=models.Q(('deleted__isnull', True)), fields=['event', 'applicable'], name='rq_evt_app_act'),
        ),
        migrations.AlterField(
            model_name='registrationquestion',
            name='typ',
            field=models.CharField(choices=[('s', 'Single choice'), ('m', 'Multiple choice'), ('t', 'Single-line text'), ('p', 'Multi-line text'), ('e', 'Advanced text editor'), ('ticket', 'Ticket'), ('additional_tickets', 'Additional'), ('pay_what_you_want', 'Pay what you want'), ('reg_quotas', 'Rate'), ('reg_surcharges', 'Surcharge'), ('faction_preference', 'Faction preference')], default='s', help_text='Question type', max_length=50, verbose_name='Type'),
        ),
    ]
