# Generated by Django 5.2.7 on 2026-07-29 13:06

import django.core.validators
import django.db.models.deletion
import larpmanager.models.utils
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0182_registration_approval_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilityexp',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Enter the prerequisite abilities, which must be possessed before one can acquire this', related_name='exp_ability_unlock', to='larpmanager.abilityexp', verbose_name='Pre-requisites'),
        ),
        migrations.AlterField(
            model_name='abilityexp',
            name='requirements',
            field=models.ManyToManyField(blank=True, help_text='Enter the character options, which must be selected to make the ability available', related_name='abilities', to='larpmanager.writingoption', verbose_name='Requirements'),
        ),
        migrations.AlterField(
            model_name='abilityexp',
            name='visible',
            field=models.BooleanField(default=True, help_text='Enter whether the ability is visible to users, and can be freely purchased'),
        ),
        migrations.AlterField(
            model_name='accountingitemexpense',
            name='balance',
            field=models.CharField(choices=[('1', 'Raw materials, auxiliaries, consumables and goods'), ('2', 'Services'), ('3', 'Use of third party assets'), ('4', 'Personal'), ('5', 'Miscellaneous operating expenses')], help_text='Enter how spending is allocated in the budget', max_length=1, null=True, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='accountingitemexpense',
            name='exp',
            field=models.CharField(choices=[('a', 'Set design: staging and materials'), ('b', 'Costumes: makeup, clothing, and armor'), ('c', 'Props: weapons and accessories'), ('d', 'Electronics: computers, high-tech equipment, and lighting'), ('e', 'Promotion: website and advertising'), ('f', 'Transportation: fuel and highway tolls'), ('g', 'Kitchen: food and tableware'), ('h', 'Venue: rent, utilities, and accommodation'), ('i', 'Secretarial: stationery and printing'), ('j', 'Other')], help_text='Enter the outflow category', max_length=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='accountingiteminflow',
            name='payment_date',
            field=models.DateField(help_text='Enter the exact date on which the payment was made', null=True, verbose_name='Payment date'),
        ),
        migrations.AlterField(
            model_name='accountingitemoutflow',
            name='balance',
            field=models.CharField(choices=[('1', 'Raw materials, auxiliaries, consumables and goods'), ('2', 'Services'), ('3', 'Use of third party assets'), ('4', 'Personal'), ('5', 'Miscellaneous operating expenses')], help_text='Enter how spending is allocated in the budget', max_length=1, null=True, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='accountingitemoutflow',
            name='exp',
            field=models.CharField(choices=[('a', 'Set design: staging and materials'), ('b', 'Costumes: makeup, clothing, and armor'), ('c', 'Props: weapons and accessories'), ('d', 'Electronics: computers, high-tech equipment, and lighting'), ('e', 'Promotion: website and advertising'), ('f', 'Transportation: fuel and highway tolls'), ('g', 'Kitchen: food and tableware'), ('h', 'Venue: rent, utilities, and accommodation'), ('i', 'Secretarial: stationery and printing'), ('j', 'Other')], help_text='Enter the outflow category', max_length=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='accountingitemoutflow',
            name='payment_date',
            field=models.DateField(help_text='Enter the exact date on which the payment was made', null=True, verbose_name='Payment date'),
        ),
        migrations.AlterField(
            model_name='association',
            name='maintainers',
            field=models.ManyToManyField(blank=True, help_text='Staff members who will receive and manage support tickets', related_name='maintained_associations', to='larpmanager.member', verbose_name='Support staff'),
        ),
        migrations.AlterField(
            model_name='association',
            name='profile',
            field=models.ImageField(blank=True, help_text="Your organization's logo (Upload an image of any size; it will be automatically optimized. Square images work best.)", max_length=500, null=True, upload_to=larpmanager.models.utils.UploadToPathAndRename('association/'), verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='associationtext',
            name='typ',
            field=models.CharField(choices=[('p', 'Profile'), ('h', 'Calendar'), ('u', 'Registration email'), ('m', 'Membership request'), ('s', 'Association Statute'), ('l', 'Legal notice'), ('f', 'Footer'), ('t', 'Terms and Conditions'), ('r', 'Receipt'), ('g', 'Mail signature'), ('y', 'Privacy'), ('rm', 'Membership request reminder email'), ('rf', 'Membership request reminder email'), ('rp', 'Payment reminder email'), ('rr', 'Profile completion reminder email')], help_text='Type of text', max_length=2, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='associationtranslation',
            name='number',
            field=models.IntegerField(blank=True, help_text='Optional sorting', null=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='character',
            name='title',
            field=models.CharField(blank=True, help_text='Enter the title of the character - it will be shown along with the name', max_length=100),
        ),
        migrations.AlterField(
            model_name='discount',
            name='max_redeem',
            field=models.IntegerField(help_text='Enter the maximum number of these discounts that can be requested (0 for unlimited uses)'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='runs',
            field=models.ManyToManyField(blank=True, help_text='Select the sessions for which the discount is active', related_name='discounts', to='larpmanager.run', verbose_name='Sessions'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enter the discount value; it will be deducted from the total amount calculated.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='discount',
            name='visible',
            field=models.BooleanField(default=False, help_text='Enter whether the discount is visible and usable by participants'),
        ),
        migrations.AlterField(
            model_name='event',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Selecting an event makes you join its campaign and share your characters with it (leave empty to start a new campaign)', null=True, on_delete=django.db.models.deletion.CASCADE, to='larpmanager.event', verbose_name='Parent campaign'),
        ),
        migrations.AlterField(
            model_name='eventtext',
            name='typ',
            field=models.CharField(choices=[('i', 'Character sheet intro'), ('t', 'Terms and conditions'), ('r', 'Registration form'), ('s', 'Search'), ('g', 'Registration email'), ('a', 'Character assignment email'), ('c', "Player's character form"), ('cs', 'Proposed character'), ('ca', 'Approved character'), ('cr', 'Character review'), ('ra', 'Registration approval request')], max_length=2, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='helpquestion',
            name='text',
            field=models.TextField(help_text='Write your question, request, or concern here. We will be happy to help!', max_length=5000, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='member',
            name='document_expiration',
            field=models.DateField(blank=True, help_text='Leave blank if the document has no expiration date. Please check that it does not expire before the event you want to sign up for.', null=True, verbose_name='Date of expiration of the document'),
        ),
        migrations.AlterField(
            model_name='member',
            name='document_type',
            field=models.CharField(choices=[('i', 'ID Card'), ('p', "Driver's License"), ('s', 'Passport')], default='i', help_text='Enter the type of identification document issued by the country where you live.', max_length=1, null=True, verbose_name='Document type'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default=None, help_text='Enter your legal gender as it appears on official documents. It will only be used for internal bureaucratic purposes, and will NEVER be displayed to other participants.', max_length=1, null=True, verbose_name='Legal Gender'),
        ),
        migrations.AlterField(
            model_name='member',
            name='legal_name',
            field=models.CharField(blank=True, help_text='If the first name shown on your documents is different from the one you prefer to use, then write it here; otherwise leave this field empty. It will only be used for internal bureaucratic purposes, and will NEVER be displayed to other participants.', max_length=100, null=True, verbose_name='Legal name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='nationality',
            field=models.CharField(blank=True, choices=[('AF', 'Afghanistan'), ('AX', 'Åland Islands'), ('AL', 'Albania'), ('DZ', 'Algeria'), ('AS', 'American Samoa'), ('AD', 'Andorra'), ('AO', 'Angola'), ('AI', 'Anguilla'), ('AQ', 'Antarctica'), ('AG', 'Antigua and Barbuda'), ('AR', 'Argentina'), ('AM', 'Armenia'), ('AW', 'Aruba'), ('AU', 'Australia'), ('AT', 'Austria'), ('AZ', 'Azerbaijan'), ('BS', 'Bahamas'), ('BH', 'Bahrain'), ('BD', 'Bangladesh'), ('BB', 'Barbados'), ('BY', 'Belarus'), ('BE', 'Belgium'), ('BZ', 'Belize'), ('BJ', 'Benin'), ('BM', 'Bermuda'), ('BT', 'Bhutan'), ('BO', 'Bolivia, Plurinational State of'), ('BQ', 'Bonaire, Sint Eustatius and Saba'), ('BA', 'Bosnia and Herzegovina'), ('BW', 'Botswana'), ('BV', 'Bouvet Island'), ('BR', 'Brazil'), ('IO', 'British Indian Ocean Territory'), ('BN', 'Brunei Darussalam'), ('BG', 'Bulgaria'), ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('KH', 'Cambodia'), ('CM', 'Cameroon'), ('CA', 'Canada'), ('CV', 'Cape Verde'), ('KY', 'Cayman Islands'), ('CF', 'Central African Republic'), ('TD', 'Chad'), ('CL', 'Chile'), ('CN', 'China'), ('CX', 'Christmas Island'), ('CC', 'Cocos (Keeling Islands)'), ('CO', 'Colombia'), ('KM', 'Comoros'), ('CG', 'Congo'), ('CD', 'Congo, The Democratic Republic of the'), ('CK', 'Cook Islands'), ('CR', 'Costa Rica'), ('CI', "Côte D'ivoire"), ('HR', 'Croatia'), ('CU', 'Cuba'), ('CW', 'Curaçao'), ('CY', 'Cyprus'), ('CZ', 'Czech Republic'), ('DK', 'Denmark'), ('DJ', 'Djibouti'), ('DM', 'Dominica'), ('DO', 'Dominican Republic'), ('EC', 'Ecuador'), ('EG', 'Egypt'), ('SV', 'El Salvador'), ('GQ', 'Equatorial Guinea'), ('ER', 'Eritrea'), ('EE', 'Estonia'), ('ET', 'Ethiopia'), ('FK', 'Falkland Islands (Malvinas)'), ('FO', 'Faroe Islands'), ('FJ', 'Fiji'), ('FI', 'Finland'), ('FR', 'France'), ('GF', 'French Guiana'), ('PF', 'French Polynesia'), ('TF', 'French Southern Territories'), ('GA', 'Gabon'), ('GM', 'Gambia'), ('GE', 'Georgia'), ('DE', 'Germany'), ('GH', 'Ghana'), ('GI', 'Gibraltar'), ('GR', 'Greece'), ('GL', 'Greenland'), ('GD', 'Grenada'), ('GP', 'Guadeloupe'), ('GU', 'Guam'), ('GT', 'Guatemala'), ('GG', 'Guernsey'), ('GN', 'Guinea'), ('GW', 'Guinea-bissau'), ('GY', 'Guyana'), ('HT', 'Haiti'), ('HM', 'Heard Island and McDonald Islands'), ('VA', 'Holy See (Vatican City State)'), ('HN', 'Honduras'), ('HK', 'Hong Kong'), ('HU', 'Hungary'), ('IS', 'Iceland'), ('IN', 'India'), ('ID', 'Indonesia'), ('IR', 'Iran, Islamic Republic of'), ('IQ', 'Iraq'), ('IE', 'Ireland'), ('IM', 'Isle of Man'), ('IL', 'Israel'), ('IT', 'Italy'), ('JM', 'Jamaica'), ('JP', 'Japan'), ('JE', 'Jersey'), ('JO', 'Jordan'), ('KZ', 'Kazakhstan'), ('KE', 'Kenya'), ('KI', 'Kiribati'), ('KP', "Korea, Democratic People's Republic of"), ('KR', 'Korea, Republic of'), ('KW', 'Kuwait'), ('KG', 'Kyrgyzstan'), ('LA', "Lao People's Democratic Republic"), ('LV', 'Latvia'), ('LB', 'Lebanon'), ('LS', 'Lesotho'), ('LR', 'Liberia'), ('LY', 'Libya'), ('LI', 'Liechtenstein'), ('LT', 'Lithuania'), ('LU', 'Luxembourg'), ('MO', 'Macao'), ('MK', 'Macedonia, The Former Yugoslav Republic of'), ('MG', 'Madagascar'), ('MW', 'Malawi'), ('MY', 'Malaysia'), ('MV', 'Maldives'), ('ML', 'Mali'), ('MT', 'Malta'), ('MH', 'Marshall Islands'), ('MQ', 'Martinique'), ('MR', 'Mauritania'), ('MU', 'Mauritius'), ('YT', 'Mayotte'), ('MX', 'Mexico'), ('FM', 'Micronesia, Federated States of'), ('MD', 'Moldova, Republic of'), ('MC', 'Monaco'), ('MN', 'Mongolia'), ('ME', 'Montenegro'), ('MS', 'Montserrat'), ('MA', 'Morocco'), ('MZ', 'Mozambique'), ('MM', 'Myanmar'), ('NA', 'Namibia'), ('NR', 'Nauru'), ('NP', 'Nepal'), ('NL', 'Netherlands'), ('NC', 'New Caledonia'), ('NZ', 'New Zealand'), ('NI', 'Nicaragua'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('NU', 'Niue'), ('NF', 'Norfolk Island'), ('MP', 'Northern Mariana Islands'), ('NO', 'Norway'), ('OM', 'Oman'), ('PK', 'Pakistan'), ('PW', 'Palau'), ('PS', 'Palestinian Territory, Occupied'), ('PA', 'Panama'), ('PG', 'Papua New Guinea'), ('PY', 'Paraguay'), ('PE', 'Peru'), ('PH', 'Philippines'), ('PN', 'Pitcairn'), ('PL', 'Poland'), ('PT', 'Portugal'), ('PR', 'Puerto Rico'), ('QA', 'Qatar'), ('RE', 'Réunion'), ('RO', 'Romania'), ('RU', 'Russian Federation'), ('RW', 'Rwanda'), ('BL', 'Saint Barthélemy'), ('SH', 'Saint Helena, Ascension and Tristan Da Cunha'), ('KN', 'Saint Kitts and Nevis'), ('LC', 'Saint Lucia'), ('MF', 'Saint Martin (French Part)'), ('PM', 'Saint Pierre and Miquelon'), ('VC', 'Saint Vincent and the Grenadines'), ('WS', 'Samoa'), ('SM', 'San Marino'), ('ST', 'Sao Tome and Principe'), ('SA', 'Saudi Arabia'), ('SN', 'Senegal'), ('RS', 'Serbia'), ('SC', 'Seychelles'), ('SL', 'Sierra Leone'), ('SG', 'Singapore'), ('SX', 'Sint Maarten (Dutch Part)'), ('SK', 'Slovakia'), ('SI', 'Slovenia'), ('SB', 'Solomon Islands'), ('SO', 'Somalia'), ('ZA', 'South Africa'), ('GS', 'South Georgia and the South Sandwich Islands'), ('SS', 'South Sudan'), ('ES', 'Spain'), ('LK', 'Sri Lanka'), ('SD', 'Sudan'), ('SR', 'Suriname'), ('SJ', 'Svalbard and Jan Mayen'), ('SZ', 'Swaziland'), ('SE', 'Sweden'), ('CH', 'Switzerland'), ('SY', 'Syrian Arab Republic'), ('TW', 'Taiwan, Province of China'), ('TJ', 'Tajikistan'), ('TZ', 'Tanzania, United Republic of'), ('TH', 'Thailand'), ('TL', 'Timor-leste'), ('TG', 'Togo'), ('TK', 'Tokelau'), ('TO', 'Tonga'), ('TT', 'Trinidad and Tobago'), ('TN', 'Tunisia'), ('TR', 'Turkey'), ('TM', 'Turkmenistan'), ('TC', 'Turks and Caicos Islands'), ('TV', 'Tuvalu'), ('UG', 'Uganda'), ('UA', 'Ukraine'), ('AE', 'United Arab Emirates'), ('GB', 'United Kingdom'), ('US', 'United States'), ('UM', 'United States Minor Outlying Islands'), ('UY', 'Uruguay'), ('UZ', 'Uzbekistan'), ('VU', 'Vanuatu'), ('VE', 'Venezuela, Bolivarian Republic of'), ('VN', 'Viet Nam'), ('VG', 'Virgin Islands, British'), ('VI', 'Virgin Islands, U.S.'), ('WF', 'Wallis and Futuna'), ('EH', 'Western Sahara'), ('YE', 'Yemen'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe')], help_text='Enter the country of which you are a citizen', max_length=2, null=True, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='member',
            name='pronoun',
            field=models.CharField(blank=True, help_text='Enter the pronouns you want others to use when referring to you', max_length=20, null=True, verbose_name='Pronouns'),
        ),
        migrations.AlterField(
            model_name='member',
            name='social_contact',
            field=models.CharField(blank=True, help_text='Indicates a way for other participants to contact you. It can be an email address, a social profile, or anything else you choose. It will be made public to other participants.', max_length=150, null=True, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='invoice',
            field=models.FileField(blank=True, help_text='Statement issued by the bank as proof of the transfer (as a PDF file)', null=True, upload_to=larpmanager.models.utils.UploadToPathAndRename('wire/'), verbose_name='Bank Statement'),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enter the amount of reimbursement desired', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Refund'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='additionals',
            field=models.IntegerField(default=0, help_text='Number of additional participants', verbose_name='Additional tickets'),
        ),
        migrations.AlterField(
            model_name='registrationcharacterrel',
            name='custom_private',
            field=models.TextField(blank=True, help_text='Indicates private information about your character, visible only to you and the organizers.', max_length=5000, null=True, verbose_name='Private'),
        ),
        migrations.AlterField(
            model_name='registrationcharacterrel',
            name='custom_public',
            field=models.TextField(blank=True, help_text='Enter public information about your character, which will be shown to all other participants', max_length=5000, null=True, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='registrationcharacterrel',
            name='custom_song',
            field=models.URLField(blank=True, help_text='Enter a song you want to dedicate to your character', max_length=100, null=True, verbose_name='Song'),
        ),
        migrations.AlterField(
            model_name='registrationinstallment',
            name='tickets',
            field=models.ManyToManyField(blank=True, help_text='Enter the tickets for which it is active', related_name='installments', to='larpmanager.registrationticket', verbose_name='Tickets'),
        ),
        migrations.AlterField(
            model_name='registrationquestion',
            name='giftable',
            field=models.BooleanField(default=False, help_text='Enter whether the option can be included in the gifted signups', verbose_name='Giftable'),
        ),
        migrations.AlterField(
            model_name='ruleexp',
            name='abilities',
            field=models.ManyToManyField(blank=True, help_text='The rule will be applied only once if the character has any of the abilities. If no abilities are chosen, it applies to all characters.', related_name='rules', to='larpmanager.abilityexp'),
        ),
        migrations.AlterField(
            model_name='run',
            name='registration_open',
            field=models.DateTimeField(blank=True, help_text='Date and time of status change', null=True, verbose_name='Registration date'),
        ),
        migrations.AlterField(
            model_name='shuttleservice',
            name='address',
            field=models.TextField(help_text='Provide as precise a location or address as possible for pickup.', verbose_name='Pickup location'),
        ),
        migrations.AlterField(
            model_name='shuttleservice',
            name='date',
            field=models.DateField(help_text='The date transportation is needed.', verbose_name='Pickup date'),
        ),
        migrations.AlterField(
            model_name='shuttleservice',
            name='info',
            field=models.TextField(help_text='Include identifying details (e.g., clothing, luggage, precise meeting point) to help us locate you.', verbose_name='Additional details'),
        ),
        migrations.AlterField(
            model_name='shuttleservice',
            name='notes',
            field=models.TextField(help_text='Information for passengers (such as car color/model, estimated arrival time).', null=True, verbose_name='Passenger instructions'),
        ),
        migrations.AlterField(
            model_name='shuttleservice',
            name='passengers',
            field=models.IntegerField(help_text='Number of passengers requiring transportation.', verbose_name='Number of passengers'),
        ),
        migrations.AlterField(
            model_name='shuttleservice',
            name='time',
            field=models.TimeField(help_text='The time transportation is needed (local event time zone).', verbose_name='Pickup time'),
        ),
        migrations.AlterField(
            model_name='writingoption',
            name='requirements',
            field=models.ManyToManyField(blank=True, help_text='Enter other options that must be selected for this option to be selectable', related_name='dependents_inv', to='larpmanager.writingoption', verbose_name='Prerequisites'),
        ),
        migrations.AlterField(
            model_name='writingquestion',
            name='printable',
            field=models.BooleanField(default=True, help_text='Enter whether the field is printed in PDF generations', verbose_name='Printable'),
        ),
        migrations.AlterField(
            model_name='registrationcharacterrel',
            name='custom_private',
            field=models.TextField(blank=True,
                                   help_text='Indicates private information about your character, visible only to you and the organizers',
                                   max_length=5000, null=True, verbose_name='Private'),
        ),
        migrations.AlterField(
            model_name='abilityexp',
            name='prerequisites',
            field=models.ManyToManyField(blank=True,
                                         help_text='The prerequisite abilities, which must be possessed before one can acquire this',
                                         related_name='exp_ability_unlock', to='larpmanager.abilityexp',
                                         verbose_name='Pre-requisites'),
        ),
        migrations.AlterField(
            model_name='abilityexp',
            name='requirements',
            field=models.ManyToManyField(blank=True,
                                         help_text='The character options, which must be selected to make the ability available',
                                         related_name='abilities', to='larpmanager.writingoption',
                                         verbose_name='Requirements'),
        ),
        migrations.AlterField(
            model_name='accountingitemexpense',
            name='exp',
            field=models.CharField(
                choices=[('a', 'Set design: staging and materials'), ('b', 'Costumes: makeup, clothing, and armor'),
                         ('c', 'Props: weapons and accessories'),
                         ('d', 'Electronics: computers, high-tech equipment, and lighting'),
                         ('e', 'Promotion: website and advertising'), ('f', 'Transportation: fuel and highway tolls'),
                         ('g', 'Kitchen: food and tableware'), ('h', 'Venue: rent, utilities, and accommodation'),
                         ('i', 'Secretarial: stationery and printing'), ('j', 'Other')],
                help_text='The outflow category', max_length=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='accountingiteminflow',
            name='payment_date',
            field=models.DateField(help_text='The exact date on which the payment was made', null=True,
                                   verbose_name='Payment date'),
        ),
        migrations.AlterField(
            model_name='accountingitemoutflow',
            name='exp',
            field=models.CharField(
                choices=[('a', 'Set design: staging and materials'), ('b', 'Costumes: makeup, clothing, and armor'),
                         ('c', 'Props: weapons and accessories'),
                         ('d', 'Electronics: computers, high-tech equipment, and lighting'),
                         ('e', 'Promotion: website and advertising'), ('f', 'Transportation: fuel and highway tolls'),
                         ('g', 'Kitchen: food and tableware'), ('h', 'Venue: rent, utilities, and accommodation'),
                         ('i', 'Secretarial: stationery and printing'), ('j', 'Other')],
                help_text='The outflow category', max_length=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='accountingitemoutflow',
            name='payment_date',
            field=models.DateField(help_text='The exact date on which the payment was made', null=True,
                                   verbose_name='Payment date'),
        ),
        migrations.AlterField(
            model_name='character',
            name='mirror',
            field=models.OneToOneField(blank=True,
                                       help_text='Whether the character is a mirror (i.e., whether this pg shows the true secret face of another character)',
                                       null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='mirror_inv', to='larpmanager.character'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='cod',
            field=models.CharField(default=larpmanager.models.utils.my_uuid_short,
                                   help_text='Unique promotional code to share with participants for use during registration',
                                   max_length=12, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='max_redeem',
            field=models.IntegerField(help_text='The maximum number of uses (0 for unlimited uses)'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='only_reg',
            field=models.BooleanField(default=True,
                                      help_text='Whether the discount can be used only on new enrollment, or whether it can be used by already registered participants.'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='typ',
            field=models.CharField(
                choices=[('a', 'Standard'), ('p', 'Play Again'), ('f', 'Friend'), ('I', 'Influencer'), ('g', 'Gift')],
                help_text='The type of discount: standard, play again (only available to those who have already played this event)',
                max_length=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0,
                                      help_text='The discount value; it will be deducted from the total registration fee',
                                      max_digits=10,
                                      validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='faction',
            name='selectable',
            field=models.BooleanField(default=False, help_text='Whether the faction can be selected by participants'),
        ),
        migrations.AlterField(
            model_name='member',
            name='social_contact',
            field=models.CharField(blank=True,
                                   help_text='Enter a way for other participants to contact you. It can be an email address, a social profile, or anything else you choose. It will be made public to other participants.',
                                   max_length=150, null=True, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='compiled',
            field=models.BooleanField(default=False,
                                      help_text='Whether the member has completed their profile information',
                                      verbose_name='Profile completed'),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='details',
            field=models.TextField(
                help_text='Enter all references of how you want your refund to be paid  (ex: IBAN and full bank details, paypal link, etc)',
                max_length=2000, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='registrationcharacterrel',
            name='custom_private',
            field=models.TextField(blank=True,
                                   help_text='Enter private information about your character, visible only to you and the organizers',
                                   max_length=5000, null=True, verbose_name='Private'),
        ),
        migrations.AlterField(
            model_name='registrationinstallment',
            name='tickets',
            field=models.ManyToManyField(blank=True, help_text='The tickets for which it is active',
                                         related_name='installments', to='larpmanager.registrationticket',
                                         verbose_name='Tickets'),
        ),
        migrations.AlterField(
            model_name='registrationquestion',
            name='typ',
            field=models.CharField(choices=[('s', 'Single choice'), ('m', 'Multiple choice'), ('t', 'Single-line text'),
                                            ('p', 'Multi-line text'), ('e', 'Advanced text editor'),
                                            ('ticket', 'Ticket'), ('additional_tickets', 'Additional'),
                                            ('pay_what_you_want', 'Pay what you want'),
                                            ('reg_quotas', 'Payment Installments'), ('reg_surcharges', 'Surcharge'),
                                            ('faction_preference', 'Faction preference')], default='s',
                                   help_text='Question type', max_length=50, verbose_name='Type'),
        ),
    ]
