# Generated by Django 5.2.7 on 2026-07-30 10:38

import django.db.models.deletion
import django.utils.timezone
import model_clone.mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0183_alter_abilityexp_prerequisites_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uuid', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('order', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('symmetric', models.BooleanField(default=True, help_text="If checked, applying this tag to a relationship also applies it to the other character's relationship back towards this one", verbose_name='Symmetric')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='larpmanager.event')),
            ],
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.AddField(
            model_name='relationship',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='relationships', to='larpmanager.relationshiptag'),
        ),
        migrations.AddIndex(
            model_name='relationshiptag',
            index=models.Index(fields=['number', 'event'], name='larpmanager_number_261d77_idx'),
        ),
        migrations.AddConstraint(
            model_name='relationshiptag',
            constraint=models.UniqueConstraint(fields=('event', 'number', 'deleted'), name='unique_RelationshipTag_with_optional'),
        ),
        migrations.AddConstraint(
            model_name='relationshiptag',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', None)), fields=('event', 'number'), name='unique_RelationshipTag_without_optional'),
        ),
    ]
