# Generated by Django 5.2.7 on 2026-08-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0185_remove_payment_invoices_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationticket',
            name='show_sold',
            field=models.BooleanField(default=False, help_text='Optional - Indicates whether to show on the event page how many of this ticket have been sold', verbose_name='Show sold count'),
        ),
        migrations.AlterField(
            model_name='associationtext',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('it', 'Italiano'), ('es', 'Español'), ('de', 'Deutsch'),
                                            ('fr', 'Français'), ('cs', 'Čeština'), ('pl', 'Polski'),
                                            ('nl', 'Nederlands'), ('nb', 'Norsk'), ('sv', 'Svenska'), ('fi', 'suomi'),
                                            ('pt', 'Português')], default='en', help_text='Text language', max_length=3,
                                   null=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='associationtranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('it', 'Italiano'), ('es', 'Español'), ('de', 'Deutsch'),
                                            ('fr', 'Français'), ('cs', 'Čeština'), ('pl', 'Polski'),
                                            ('nl', 'Nederlands'), ('nb', 'Norsk'), ('sv', 'Svenska'), ('fi', 'suomi'),
                                            ('pt', 'Português')],
                                   help_text="ISO language code (e.g., 'en', 'it', 'de')", max_length=3,
                                   verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='eventtext',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('it', 'Italiano'), ('es', 'Español'), ('de', 'Deutsch'),
                                            ('fr', 'Français'), ('cs', 'Čeština'), ('pl', 'Polski'),
                                            ('nl', 'Nederlands'), ('nb', 'Norsk'), ('sv', 'Svenska'), ('fi', 'suomi'),
                                            ('pt', 'Português')], default='en', help_text='Text language', max_length=3,
                                   null=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='member',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('it', 'Italiano'), ('es', 'Español'), ('de', 'Deutsch'),
                                            ('fr', 'Français'), ('cs', 'Čeština'), ('pl', 'Polski'),
                                            ('nl', 'Nederlands'), ('nb', 'Norsk'), ('sv', 'Svenska'), ('fi', 'suomi'),
                                            ('pt', 'Português')], default='en',
                                   help_text='Preferred navigation language', max_length=3, null=True,
                                   verbose_name='Navigation language'),
        ),
    ]
