# Generated by Django 5.2.7 on 2026-08-12 08:38

import django.utils.timezone
import model_clone.mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0186_registrationticket_show_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSuppression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('reason', models.CharField(choices=[('b', 'Permanent bounce'), ('t', 'Transient bounce'), ('c', 'Complaint'), ('m', 'Manual')], max_length=1, verbose_name='Reason')),
                ('bounce_count', models.PositiveIntegerField(default=1, verbose_name='Bounce Count')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('last_event', models.DateTimeField(auto_now=True, verbose_name='Last Event')),
                ('raw', models.JSONField(blank=True, null=True, verbose_name='Raw Payload')),
            ],
            options={
                'ordering': ['-updated'],
                'abstract': False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.AddField(
            model_name='emailrecipient',
            name='skipped',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Skipped'),
        ),
        migrations.AddField(
            model_name='emailcontent',
            name='bulk',
            field=models.BooleanField(default=False, verbose_name='Bulk'),
        ),
    ]
