# Generated by Django 5.2.7 on 2026-08-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0188_guild_secret_alter_associationtext_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingquestion',
            name='requirements',
            field=models.ManyToManyField(blank=True, help_text='Enter other options that must be selected for this question to be shown', related_name='gated_questions', to='larpmanager.writingoption', verbose_name='Prerequisites'),
        ),
    ]
