# Generated by Django 5.2.7 on 2026-08-15 21:01

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.contrib.postgres.search import SearchVector
from django.db import migrations
from django.db.models import TextField, Value
from django.db.models.functions import Cast, Coalesce


def populate_search_vector(apps, schema_editor):
    """Populate search_vector from the ticket text fields."""
    LarpManagerTicket = apps.get_model("larpmanager", "LarpManagerTicket")
    LarpManagerTicket.objects.update(
        search_vector=SearchVector(
            Cast(Coalesce("subject", Value("")), TextField()),
            Cast(Coalesce("reason", Value("")), TextField()),
            Cast(Coalesce("content", Value("")), TextField()),
            Cast(Coalesce("analysis", Value("")), TextField()),
            Cast(Coalesce("transcript", Value("")), TextField()),
            config="english",
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ("larpmanager", "0188_alter_associationtext_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="larpmanagerticket",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name="larpmanagerticket",
            index=django.contrib.postgres.indexes.GinIndex(fields=["search_vector"], name="ticket_search_vector_idx"),
        ),
        migrations.RunPython(populate_search_vector, migrations.RunPython.noop),
        migrations.RunSQL(
            sql="""
            CREATE FUNCTION larpmanagerticket_search_vector_update() RETURNS trigger AS $$
            BEGIN
                NEW.search_vector := to_tsvector('pg_catalog.english',
                    coalesce(NEW.subject, '') || ' ' ||
                    coalesce(NEW.reason, '') || ' ' ||
                    coalesce(NEW.content, '') || ' ' ||
                    coalesce(NEW.analysis, '') || ' ' ||
                    coalesce(NEW.transcript, ''));
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER larpmanagerticket_search_vector_update
            BEFORE INSERT OR UPDATE ON larpmanager_larpmanagerticket
            FOR EACH ROW EXECUTE FUNCTION larpmanagerticket_search_vector_update();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS larpmanagerticket_search_vector_update ON larpmanager_larpmanagerticket;
            DROP FUNCTION IF EXISTS larpmanagerticket_search_vector_update();
            """,
        ),
    ]
