# Generated by Django 5.2.7 on 2026-08-16 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0189_larpmanagerticket_search_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisherapikey',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='larpmanager.association'),
        ),
        migrations.AddField(
            model_name='publisherapikey',
            name='scopes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
