# Generated by Django 5.2.7 on 2026-08-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0189_writingquestion_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingoption',
            name='default',
            field=models.BooleanField(default=False, help_text='Indicate whether this option is assigned automatically, when the question cannot be answered by the participant and no option was chosen; if several options are marked, the first one whose prerequisites are satisfied is assigned', verbose_name='Default'),
        ),
    ]
