# Generated by Django 5.2.7 on 2026-08-16 07:44

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
import model_clone.mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0190_publisherapikey_association_publisherapikey_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='larpmanagerticket',
            name='last_synced_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='larpmanagerticket',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status changed'), ('priority_changed', 'Priority changed'), ('assigned', 'Assigned'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('deleted', 'Deleted'), ('channel_create', 'Channel create'), ('channel_synced', 'Channel synced'), ('channel_update', 'Channel update'), ('channel_archive', 'Channel archive'), ('access_denied', 'Access denied')], max_length=32)),
                ('source', models.CharField(choices=[('api', 'API'), ('discord', 'Discord')], max_length=16)),
                ('from_status', models.CharField(blank=True, max_length=20, null=True)),
                ('to_status', models.CharField(blank=True, max_length=20, null=True)),
                ('actor_discord_id', models.BigIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('actor_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='larpmanager.member')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='larpmanager.larpmanagerticket')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['source', 'applied_at', 'acked_at'], name='ticket_event_outbox_idx')],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uuid', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('discord_message_id', models.BigIntegerField(unique=True)),
                ('author_discord_id', models.BigIntegerField(blank=True, null=True)),
                ('author_name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('is_bot', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='larpmanager.larpmanagerticket')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='ticket_msg_search_vector_idx')],
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
    ]
