# Generated by Django 5.2.7 on 2026-08-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0192_ticket_transcript_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='larpmanagerticket',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Client-supplied key used to deduplicate API ticket creation', max_length=255, null=True, unique=True, verbose_name='Idempotency Key'),
        ),
    ]
