# Generated by Django 5.2.7 on 2026-08-17 18:48

import django.db.models.deletion
import django.utils.timezone
import larpmanager.models.ticket_transcript_link
import model_clone.mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0193_larpmanagerticket_idempotency_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTranscriptLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uuid', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, default=larpmanager.models.ticket_transcript_link.generate_transcript_token, editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('max_opens', models.PositiveSmallIntegerField(default=5)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='larpmanager.association')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transcript_links', to='larpmanager.member')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_links', to='larpmanager.larpmanagerticket')),
            ],
            options={
                'ordering': ['-created'],
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
    ]
