# Generated by Django 5.2.7 on 2026-08-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0194_tickettranscriptlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status changed'), ('priority_changed', 'Priority changed'), ('assigned', 'Assigned'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('deleted', 'Deleted'), ('channel_create', 'Channel create'), ('channel_synced', 'Channel synced'), ('channel_update', 'Channel update'), ('channel_archive', 'Channel archive'), ('access_denied', 'Access denied'), ('reply', 'Reply')], max_length=32),
        ),
    ]
