# Generated by Django 5.2.7 on 2026-08-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0195_alter_ticketevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmessage',
            name='discord_message_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
