# Generated by Django 5.2.7 on 2026-08-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0196_alter_ticketmessage_discord_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='larpmanagerticket',
            name='ticket_type',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10, verbose_name='Type'),
        ),
    ]
