# Generated by Django 5.2.7 on 2026-08-19 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0197_larpmanagerticket_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='larpmanagerticket',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_tickets', to='larpmanager.larpmanagerticket', verbose_name='Merged into'),
        ),
        migrations.AddField(
            model_name='larpmanagerticket',
            name='stranded',
            field=models.BooleanField(default=False, verbose_name='Stranded'),
        ),
        migrations.AlterField(
            model_name='ticketevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status changed'), ('priority_changed', 'Priority changed'), ('assigned', 'Assigned'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('deleted', 'Deleted'), ('channel_create', 'Channel create'), ('channel_synced', 'Channel synced'), ('channel_update', 'Channel update'), ('channel_archive', 'Channel archive'), ('access_denied', 'Access denied'), ('reply', 'Reply'), ('merged', 'Merged'), ('stranded', 'Stranded')], max_length=32),
        ),
    ]
