# Generated by Django 5.2.7 on 2026-08-25 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0190_writingoption_default'),
        ('larpmanager', '0198_larpmanagerticket_merged_into_and_more'),
    ]

    operations = [
    ]
