# Generated by Django 5.2.7 on 2026-08-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0199_merge_20260825_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationtext',
            name='typ',
            field=models.CharField(choices=[('p', 'Profile'), ('h', 'Calendar'), ('u', 'Registration email'), ('m', 'Membership request'), ('s', 'Association Statute'), ('l', 'Legal notice'), ('f', 'Footer'), ('t', 'Terms and Conditions'), ('r', 'Receipt'), ('g', 'Mail signature'), ('y', 'Privacy'), ('rm', 'Membership request reminder email'), ('rf', 'Membership request reminder email'), ('rp', 'Payment reminder email'), ('rr', 'Profile completion reminder email'), ('rc', 'Character creation reminder email')], help_text='Type of text', max_length=2, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='registrationquestion',
            name='status',
            field=models.CharField(choices=[('o', 'Optional'), ('m', 'Mandatory'), ('d', 'Read only'), ('h', 'Hidden')], default='o', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='writingquestion',
            name='status',
            field=models.CharField(choices=[('o', 'Optional'), ('m', 'Mandatory'), ('d', 'Read only'), ('h', 'Hidden')], default='o', max_length=1, verbose_name='Status'),
        ),
    ]
