# LarpManager - https://larpmanager.com
# Copyright (C) 2025 Scanagatta Mauro
#
# This file is part of LarpManager and is dual-licensed:
#
# 1. Under the terms of the GNU Affero General Public License (AGPL) version 3,
#    as published by the Free Software Foundation. You may use, modify, and
#    distribute this file under those terms.
#
# 2. Under a commercial license, allowing use in closed-source or proprietary
#    environments without the obligations of the AGPL.
#
# If you have obtained this file under the AGPL, and you make it available over
# a network, you must also make the complete source code available under the same license.
#
# For more information or to purchase a commercial license, contact:
# commercial@larpmanager.com
#
# SPDX-License-Identifier: AGPL-3.0-or-later OR Proprietary


from django.urls import path

from larpmanager.views.user import casting as views_uca
from larpmanager.views.user import character as views_uc
from larpmanager.views.user import event as views_ue
from larpmanager.views.user import miscellanea as views_ums
from larpmanager.views.user import pdf as views_up
from larpmanager.views.user import registration as views_ur

urlpatterns = [
    path(
        "<slug:event_slug>/",
        views_ue.gallery,
        name="gallery",
    ),
    path(
        "<slug:event_slug>/event/",
        views_ue.event,
        name="event",
    ),
    path(
        "<slug:event_slug>/event/register/",
        views_ue.event_register,
        name="event_register",
    ),
    path(
        "<slug:event_slug>/character/list/",
        views_uc.character_list,
        name="character_list",
    ),
    path(
        "<slug:event_slug>/character/list/json/",
        views_uc.character_list_json,
        name="character_list_json",
    ),
    path(
        "<slug:event_slug>/character/create/",
        views_uc.character_create,
        name="character_create",
    ),
    path(
        "<slug:event_slug>/character/your/",
        views_uc.character_your,
        name="character_your",
    ),
    path(
        "<slug:event_slug>/character/your/<path:path>",
        views_uc.character_your,
        name="character_your",
    ),
    path(
        "<slug:event_slug>/character/external/<slug:code>/",
        views_uc.character_external,
        name="character_external",
    ),
    path(
        "<slug:event_slug>/character/<slug:character_uuid>/",
        views_uc.character_view,
        name="character",
    ),
    path(
        "<slug:event_slug>/character/<slug:character_uuid>/change/",
        views_uc.character_edit,
        name="character_change",
    ),
    path(
        "<slug:event_slug>/character/<slug:character_uuid>/customize/",
        views_uc.character_customize,
        name="character_customize",
    ),
    path(
        "<slug:event_slug>/character/<slug:character_uuid>/profile/rotate/<int:rotation_angle>/",
        views_uc.character_profile_rotate,
        name="character_profile_rotate",
    ),
    path(
        "<slug:event_slug>/character/<slug:character_uuid>/profile/upload/",
        views_uc.character_profile_upload,
        name="character_profile_upload",
    ),
    path(
        "<slug:event_slug>/character/<slug:character_uuid>/abilities/",
        views_uc.character_abilities,
        name="character_abilities",
    ),
    path(
        "<slug:event_slug>/character/<slug:character_uuid>/abilities/json/",
        views_uc.character_abilities_json,
        name="character_abilities_json",
    ),
    path(
        "<slug:event_slug>/character/<slug:character_uuid>/abilities/<slug:ability_uuid>/",
        views_uc.character_abilities_del,
        name="character_abilities_del",
    ),
    path(
        "<slug:event_slug>/character/<slug:character_uuid>/inventory/json/",
        views_uc.character_inventory_json,
        name="character_inventory_json",
    ),
    path(
        "<slug:event_slug>/character/<slug:character_uuid>/assign/",
        views_uc.character_assign,
        name="character_assign",
    ),
    path(
        "<slug:event_slug>/character/<slug:character_uuid>/relationships/",
        views_uc.character_relationships,
        name="character_relationships",
    ),
    path(
        "<slug:event_slug>/character/<slug:character_uuid>/relationships/edit/<slug:other_character_uuid>",
        views_uc.character_relationships_edit,
        name="character_relationships_edit",
    ),
    path(
        "<slug:event_slug>/character/<slug:character_uuid>/pdf/sheet/",
        views_up.character_pdf_sheet,
        name="character_pdf_sheet",
    ),
    path(
        "<slug:event_slug>/character/<slug:character_uuid>/pdf/friendly/",
        views_up.character_pdf_sheet_friendly,
        name="character_pdf_sheet_friendly",
    ),
    path(
        "<slug:event_slug>/character/<slug:character_uuid>/pdf/relationships/",
        views_up.character_pdf_relationships,
        name="character_pdf_relationships",
    ),
    path(
        "<slug:event_slug>/search/",
        views_ue.search,
        name="search",
    ),
    path(
        "<slug:event_slug>/limitations/",
        views_ue.limitations,
        name="limitations",
    ),
    path(
        "<slug:event_slug>/gift/",
        views_ur.gift,
        name="gift",
    ),
    path(
        "<slug:event_slug>/gift/edit/<slug:gift_uuid>/",
        views_ur.gift_edit,
        name="gift_edit",
    ),
    path(
        "<slug:event_slug>/gift/redeem/<slug:code>/",
        views_ur.gift_redeem,
        name="gift_redeem",
    ),
    path(
        "<slug:event_slug>/casting/",
        views_uca.casting,
        name="casting",
    ),
    path(
        "<slug:event_slug>/casting/<str:casting_type>/",
        views_uca.casting,
        name="casting",
    ),
    path(
        "<slug:event_slug>/casting/preferences/",
        views_uca.casting_preferences,
        name="casting_preferences",
    ),
    path(
        "<slug:event_slug>/casting/preferences/<str:casting_type>/",
        views_uca.casting_preferences,
        name="casting_preferences",
    ),
    path(
        "<slug:event_slug>/casting/history/",
        views_uca.casting_history,
        name="casting_history",
    ),
    path(
        "<slug:event_slug>/casting/history/<str:casting_type>/",
        views_uca.casting_history,
        name="casting_history",
    ),
    path(
        "<slug:event_slug>/factions/",
        views_ue.factions,
        name="factions",
    ),
    path(
        "<slug:event_slug>/faction/<slug:faction_uuid>/",
        views_ue.faction,
        name="faction",
    ),
    path(
        "<slug:event_slug>/quests/",
        views_ue.quests,
        name="quests",
    ),
    path(
        "<slug:event_slug>/quests/<slug:quest_type_uuid>/",
        views_ue.quests,
        name="quests",
    ),
    path(
        "<slug:event_slug>/quest/<slug:quest_uuid>/",
        views_ue.quest,
        name="quest",
    ),
    path(
        "<slug:event_slug>/album/",
        views_ums.album,
        name="album",
    ),
    path(
        "<slug:event_slug>/album/<slug:album_uuid>/",
        views_ums.album_sub,
        name="album_sub",
    ),
    path(
        "<slug:event_slug>/export/<slug:export_type>/",
        views_ue.export,
        name="export",
    ),
    path(
        "<slug:event_slug>/handout/<slug:code>/",
        views_ums.handout_ext,
        name="handout_ext",
    ),
    path(
        "<slug:event_slug>/portraits/",
        views_up.portraits,
        name="portraits",
    ),
    path(
        "<slug:event_slug>/profiles/",
        views_up.profiles,
        name="profiles",
    ),
    path(
        "<slug:event_slug>/register/pre/",
        views_ur.pre_register,
        name="pre_register",
    ),
    path(
        "<slug:event_slug>/register/conditions/",
        views_ur.register_conditions,
        name="register_conditions",
    ),
    path(
        "<slug:event_slug>/register/",
        views_ur.register,
        name="register",
    ),
    path(
        "<slug:event_slug>/register/discount/<slug:discount_code>/",
        views_ur.register,
        name="register",
    ),
    path(
        "<slug:event_slug>/register/ticket/<slug:ticket_uuid>/",
        views_ur.register,
        name="register",
    ),
    path(
        "<slug:event_slug>/register/reduced/",
        views_ur.register_reduced,
        name="register_reduced",
    ),
    path(
        "<slug:event_slug>/register/<slug:secret_code>/",
        views_ur.register_exclusive,
        name="register_exclusive",
    ),
    path(
        "<slug:event_slug>/register/<slug:secret_code>/discount/<slug:discount_code>/",
        views_ur.register_exclusive,
        name="register_exclusive",
    ),
    path(
        "<slug:event_slug>/discount/",
        views_ur.discount,
        name="discount",
    ),
    path(
        "<slug:event_slug>/discount/list",
        views_ur.discount_list,
        name="discount_list",
    ),
    path(
        "<slug:event_slug>/unregister/",
        views_ur.unregister,
        name="unregister",
    ),
    path(
        "<slug:event_slug>/workshops/",
        views_ums.workshops,
        name="workshops",
    ),
    path(
        "<slug:event_slug>/workshops/answer/<slug:module_uuid>/",
        views_ums.workshop_answer,
        name="workshop_answer",
    ),
    path(
        "<slug:event_slug>/help/",
        views_ums.user_help,
        name="help",
    ),
    path(
        "<slug:event_slug>/show_char/",
        views_uc.show_char,
        name="show_char",
    ),
]
