# LarpManager - https://larpmanager.com
# Copyright (C) 2025 Scanagatta Mauro
#
# This file is part of LarpManager and is dual-licensed:
#
# 1. Under the terms of the GNU Affero General Public License (AGPL) version 3,
#    as published by the Free Software Foundation. You may use, modify, and
#    distribute this file under those terms.
#
# 2. Under a commercial license, allowing use in closed-source or proprietary
#    environments without the obligations of the AGPL.
#
# If you have obtained this file under the AGPL, and you make it available over
# a network, you must also make the complete source code available under the same license.
#
# For more information or to purchase a commercial license, contact:
# commercial@larpmanager.com
#
# SPDX-License-Identifier: AGPL-3.0-or-later OR Proprietary

from django.urls import path

import larpmanager.views.exe.miscellanea
from larpmanager.utils.edit import backend as views_ed
from larpmanager.views import manage as views_mg
from larpmanager.views.exe import (
    accounting as views_ea,
    association as views_eas,
    event as views_ee,
    member as views_em,
    miscellanea as views_ems,
)

urlpatterns = [
    path(
        "manage/",
        views_mg.manage,
        name="manage",
    ),
    path(
        "manage/cache/",
        views_eas.exe_reload_cache,
        name="exe_reload_cache",
    ),
    path(
        "manage/quick/",
        views_eas.exe_quick,
        name="exe_quick",
    ),
    path(
        "manage/activation/",
        views_eas.exe_activation,
        name="exe_activation",
    ),
    path(
        "manage/deadlines/",
        views_ee.exe_deadlines,
        name="exe_deadlines",
    ),
    path(
        "manage/logs/",
        larpmanager.views.exe.miscellanea.exe_log,
        name="exe_log",
    ),
    path(
        "manage/trash/",
        views_ems.exe_trash,
        name="exe_trash",
    ),
    path(
        "manage/urlshortner/",
        views_ems.exe_urlshortner,
        name="exe_urlshortner",
    ),
    path(
        "manage/urlshortner/new/",
        views_ems.exe_urlshortner_new,
        name="exe_urlshortner_new",
    ),
    path(
        "manage/urlshortner/<slug:url_uuid>/edit/",
        views_ems.exe_urlshortner_edit,
        name="exe_urlshortner_edit",
    ),
    path(
        "manage/urlshortner/<slug:url_uuid>/delete/",
        views_ems.exe_urlshortner_delete,
        name="exe_urlshortner_delete",
    ),
    path(
        "manage/warehouse/containers/",
        views_ems.exe_warehouse_containers,
        name="exe_warehouse_containers",
    ),
    path(
        "manage/warehouse/containers/new/",
        views_ems.exe_warehouse_containers_new,
        name="exe_warehouse_containers_new",
    ),
    path(
        "manage/warehouse/containers/<slug:container_uuid>/edit/",
        views_ems.exe_warehouse_containers_edit,
        name="exe_warehouse_containers_edit",
    ),
    path(
        "manage/warehouse/containers/<slug:container_uuid>/delete/",
        views_ems.exe_warehouse_containers_delete,
        name="exe_warehouse_containers_delete",
    ),
    path(
        "manage/warehouse/tags/",
        views_ems.exe_warehouse_tags,
        name="exe_warehouse_tags",
    ),
    path(
        "manage/warehouse/tags/new/",
        views_ems.exe_warehouse_tags_new,
        name="exe_warehouse_tags_new",
    ),
    path(
        "manage/warehouse/tags/<slug:tag_uuid>/edit/",
        views_ems.exe_warehouse_tags_edit,
        name="exe_warehouse_tags_edit",
    ),
    path(
        "manage/warehouse/tags/<slug:tag_uuid>/delete/",
        views_ems.exe_warehouse_tags_delete,
        name="exe_warehouse_tags_delete",
    ),
    path(
        "manage/warehouse/items/",
        views_ems.exe_warehouse_items,
        name="exe_warehouse_items",
    ),
    path(
        "manage/warehouse/items/new/",
        views_ems.exe_warehouse_items_new,
        name="exe_warehouse_items_new",
    ),
    path(
        "manage/warehouse/items/<slug:item_uuid>/edit/",
        views_ems.exe_warehouse_items_edit,
        name="exe_warehouse_items_edit",
    ),
    path(
        "manage/warehouse/items/<slug:item_uuid>/delete/",
        views_ems.exe_warehouse_items_delete,
        name="exe_warehouse_items_delete",
    ),
    path(
        "manage/warehouse/movements/",
        views_ems.exe_warehouse_movements,
        name="exe_warehouse_movements",
    ),
    path(
        "manage/warehouse/movements/new/",
        views_ems.exe_warehouse_movements_new,
        name="exe_warehouse_movements_new",
    ),
    path(
        "manage/warehouse/movements/<slug:movement_uuid>/edit/",
        views_ems.exe_warehouse_movements_edit,
        name="exe_warehouse_movements_edit",
    ),
    path(
        "manage/warehouse/movements/<slug:movement_uuid>/delete/",
        views_ems.exe_warehouse_movements_delete,
        name="exe_warehouse_movements_delete",
    ),
    path(
        "manage/badges/",
        views_em.exe_badges,
        name="exe_badges",
    ),
    path(
        "manage/badges/new/",
        views_em.exe_badges_new,
        name="exe_badges_new",
    ),
    path(
        "manage/badges/<slug:badge_uuid>/edit/",
        views_em.exe_badges_edit,
        name="exe_badges_edit",
    ),
    path(
        "manage/users/badges/<slug:badge_uuid>/delete/",
        views_em.exe_badges_delete,
        name="exe_badges_delete",
    ),
    path(
        "manage/badges/assign/",
        views_em.exe_badges_assign,
        name="exe_badges_assign",
    ),
    path(
        "manage/badges/toggle/",
        views_em.exe_badges_toggle,
        name="exe_badges_toggle",
    ),
    path(
        "manage/mail/send",
        views_em.exe_send_mail,
        name="exe_send_mail",
    ),
    path(
        "manage/mail/archive",
        views_em.exe_archive_email,
        name="exe_archive_email",
    ),
    path(
        "manage/mail/<slug:mail_uuid>/read/",
        views_em.exe_read_mail,
        name="exe_read_mail",
    ),
    path(
        "manage/questions/",
        views_em.exe_questions,
        name="exe_questions",
    ),
    path(
        "manage/questions/<slug:member_uuid>/answer/",
        views_em.exe_questions_answer,
        name="exe_questions_answer",
    ),
    path(
        "manage/questions/<slug:member_uuid>/close/",
        views_em.exe_questions_close,
        name="exe_questions_close",
    ),
    path(
        "manage/newsletter/",
        views_em.exe_newsletter,
        name="exe_newsletter",
    ),
    path(
        "manage/newsletter/csv/<slug:lang>/",
        views_em.exe_newsletter_csv,
        name="exe_newsletter_csv",
    ),
    path(
        "manage/organization/",
        views_eas.exe_association,
        name="exe_association",
    ),
    path(
        "manage/appearance/",
        views_eas.exe_appearance,
        name="exe_appearance",
    ),
    path(
        "manage/config/<slug:section>/",
        views_eas.exe_config,
        name="exe_config",
    ),
    path(
        "manage/config/",
        views_eas.exe_config,
        name="exe_config",
    ),
    path(
        "manage/config/<slug:slug>/on/",
        views_eas.exe_config_on,
        name="exe_config_on",
    ),
    path(
        "manage/config/<slug:slug>/off/",
        views_eas.exe_config_off,
        name="exe_config_off",
    ),
    path(
        "manage/profile/",
        views_eas.exe_profile,
        name="exe_profile",
    ),
    path(
        "manage/methods/",
        views_eas.exe_methods,
        name="exe_methods",
    ),
    path(
        "manage/texts/",
        views_eas.exe_texts,
        name="exe_texts",
    ),
    path(
        "manage/texts/new/",
        views_eas.exe_texts_new,
        name="exe_texts_new",
    ),
    path(
        "manage/texts/<slug:text_uuid>/edit/",
        views_eas.exe_texts_edit,
        name="exe_texts_edit",
    ),
    path(
        "manage/texts/<slug:text_uuid>/delete/",
        views_eas.exe_texts_delete,
        name="exe_texts_delete",
    ),
    path(
        "manage/translations/",
        views_eas.exe_translations,
        name="exe_translations",
    ),
    path(
        "manage/translations/new/",
        views_eas.exe_translations_new,
        name="exe_translations_new",
    ),
    path(
        "manage/translations/<slug:translation_uuid>/edit/",
        views_eas.exe_translations_edit,
        name="exe_translations_edit",
    ),
    path(
        "manage/translations/<slug:translation_uuid>/delete/",
        views_eas.exe_translations_delete,
        name="exe_translations_delete",
    ),
    path(
        "manage/roles/",
        views_eas.exe_roles,
        name="exe_roles",
    ),
    path(
        "manage/roles/new/",
        views_eas.exe_roles_new,
        name="exe_roles_new",
    ),
    path(
        "manage/roles/<slug:role_uuid>/edit/",
        views_eas.exe_roles_edit,
        name="exe_roles_edit",
    ),
    path(
        "manage/roles/<slug:role_uuid>/delete/",
        views_eas.exe_roles_delete,
        name="exe_roles_delete",
    ),
    path(
        "manage/roles/<slug:role_uuid>/invite/",
        views_eas.exe_roles_invite,
        name="exe_roles_invite",
    ),
    path(
        "manage/balance/",
        views_ea.exe_balance,
        name="exe_balance",
    ),
    path(
        "manage/verification/",
        views_ea.exe_verification,
        name="exe_verification",
    ),
    path(
        "manage/verification/manual/<slug:invoice_uuid>/",
        views_ea.exe_verification_manual,
        name="exe_verification_manual",
    ),
    path(
        "manage/features/",
        views_eas.exe_features,
        name="exe_features",
    ),
    path(
        "manage/features/<slug:slug>/on/",
        views_eas.exe_features_on,
        name="exe_features_on",
    ),
    path(
        "manage/features/<slug:slug>/off/",
        views_eas.exe_features_off,
        name="exe_features_off",
    ),
    path(
        "manage/pre_registrations/",
        views_ee.exe_pre_registrations,
        name="exe_pre_registrations",
    ),
    path(
        "manage/credits/",
        views_ea.exe_credits,
        name="exe_credits",
    ),
    path(
        "manage/credits/new/",
        views_ea.exe_credits_new,
        name="exe_credits_new",
    ),
    path(
        "manage/credits/<slug:credit_uuid>/edit/",
        views_ea.exe_credits_edit,
        name="exe_credits_edit",
    ),
    path(
        "manage/credits/<slug:credit_uuid>/delete/",
        views_ea.exe_credits_delete,
        name="exe_credits_delete",
    ),
    path(
        "manage/tokens/",
        views_ea.exe_tokens,
        name="exe_tokens",
    ),
    path(
        "manage/tokens/new/",
        views_ea.exe_tokens_new,
        name="exe_tokens_new",
    ),
    path(
        "manage/tokens/<slug:token_uuid>/edit/",
        views_ea.exe_tokens_edit,
        name="exe_tokens_edit",
    ),
    path(
        "manage/tokens/<slug:token_uuid>/delete/",
        views_ea.exe_tokens_delete,
        name="exe_tokens_delete",
    ),
    path(
        "manage/payments/",
        views_ea.exe_payments,
        name="exe_payments",
    ),
    path(
        "manage/payments/new/",
        views_ea.exe_payments_new,
        name="exe_payments_new",
    ),
    path(
        "manage/payments/<slug:payment_uuid>/edit/",
        views_ea.exe_payments_edit,
        name="exe_payments_edit",
    ),
    path(
        "manage/payments/<slug:payment_uuid>/delete/",
        views_ea.exe_payments_delete,
        name="exe_payments_delete",
    ),
    path(
        "manage/invoices/<slug:invoice_uuid>/delete/",
        views_ea.exe_invoices_delete,
        name="exe_invoices_delete",
    ),
    path(
        "manage/invoices/<slug:invoice_uuid>/confirm/",
        views_ea.exe_invoices_confirm,
        name="exe_invoices_confirm",
    ),
    path(
        "manage/expenses/",
        views_ea.exe_expenses,
        name="exe_expenses",
    ),
    path(
        "manage/expenses/new/",
        views_ea.exe_expenses_new,
        name="exe_expenses_new",
    ),
    path(
        "manage/expenses/<slug:expense_uuid>/edit/",
        views_ea.exe_expenses_edit,
        name="exe_expenses_edit",
    ),
    path(
        "manage/expenses/<slug:expense_uuid>/delete/",
        views_ea.exe_expenses_delete,
        name="exe_expenses_delete",
    ),
    path(
        "manage/expenses/<slug:expense_uuid>/approve/",
        views_ea.exe_expenses_approve,
        name="exe_expenses_approve",
    ),
    path(
        "manage/membership/",
        views_em.exe_membership,
        name="exe_membership",
    ),
    path(
        "manage/membership/fee",
        views_em.exe_membership_fee,
        name="exe_membership_fee",
    ),
    path(
        "manage/membership/document",
        views_em.exe_membership_document,
        name="exe_membership_document",
    ),
    path(
        "manage/membership/<slug:member_uuid>/",
        views_em.exe_member,
        name="exe_member",
    ),
    path(
        "manage/membership/<slug:member_uuid>/accounting/",
        views_em.exe_member_accounting,
        name="exe_member_accounting",
    ),
    path(
        "manage/membership/<slug:member_uuid>/registrations/",
        views_em.exe_member_registrations,
        name="exe_member_registrations",
    ),
    path(
        "manage/membership/<slug:member_uuid>/evaluation/",
        views_em.exe_membership_evaluation,
        name="exe_membership_evaluation",
    ),
    path(
        "manage/membership/<slug:member_uuid>/status/",
        views_em.exe_membership_status,
        name="exe_membership_status",
    ),
    path(
        "manage/membership/<slug:member_uuid>/request/",
        views_em.exe_membership_request,
        name="exe_membership_request",
    ),
    path(
        "manage/check_membership/",
        views_em.exe_membership_check,
        name="exe_membership_check",
    ),
    path(
        "manage/registry/",
        views_em.exe_membership_registry,
        name="exe_membership_registry",
    ),
    path(
        "manage/events/",
        views_ee.exe_events,
        name="exe_events",
    ),
    path(
        "manage/events/new/",
        views_ee.exe_events_new,
        name="exe_events_new",
    ),
    path(
        "manage/events/<slug:event_uuid>/edit/",
        views_ee.exe_events_edit,
        name="exe_events_edit",
    ),
    path(
        "manage/events/<slug:run_uuid>/delete/",
        views_ee.exe_events_delete,
        name="exe_events_delete",
    ),
    path(
        "manage/template/",
        views_ee.exe_templates,
        name="exe_templates",
    ),
    path(
        "manage/template/new/",
        views_ee.exe_templates_new,
        name="exe_templates_new",
    ),
    path(
        "manage/template/<slug:template_uuid>/edit/",
        views_ee.exe_templates_edit,
        name="exe_templates_edit",
    ),
    path(
        "manage/templates/<slug:template_uuid>/delete/",
        views_ee.exe_templates_delete,
        name="exe_templates_delete",
    ),
    path(
        "manage/template/<slug:template_uuid>/config/",
        views_ee.exe_templates_config,
        name="exe_templates_config",
    ),
    path(
        "manage/template/<slug:template_uuid>/roles/new/",
        views_ee.exe_templates_roles_new,
        name="exe_templates_roles_new",
    ),
    path(
        "manage/template/<slug:template_uuid>/roles/<slug:role_uuid>/edit/",
        views_ee.exe_templates_roles_edit,
        name="exe_templates_roles_edit",
    ),
    path(
        "manage/vote/",
        views_em.exe_vote,
        name="exe_vote",
    ),
    path(
        "manage/runs/new/",
        views_ee.exe_runs_new,
        name="exe_runs_new",
    ),
    path(
        "manage/runs/<slug:run_uuid>/edit/",
        views_ee.exe_runs_edit,
        name="exe_runs_edit",
    ),
    path(
        "manage/outflows/",
        views_ea.exe_outflows,
        name="exe_outflows",
    ),
    path(
        "manage/outflows/new/",
        views_ea.exe_outflows_new,
        name="exe_outflows_new",
    ),
    path(
        "manage/outflows/<slug:outflow_uuid>/edit/",
        views_ea.exe_outflows_edit,
        name="exe_outflows_edit",
    ),
    path(
        "manage/outflows/<slug:outflow_uuid>/delete/",
        views_ea.exe_outflows_delete,
        name="exe_outflows_delete",
    ),
    path(
        "manage/inflows/",
        views_ea.exe_inflows,
        name="exe_inflows",
    ),
    path(
        "manage/inflows/new/",
        views_ea.exe_inflows_new,
        name="exe_inflows_new",
    ),
    path(
        "manage/inflows/<slug:inflow_uuid>/edit/",
        views_ea.exe_inflows_edit,
        name="exe_inflows_edit",
    ),
    path(
        "manage/inflows/<slug:inflow_uuid>/delete/",
        views_ea.exe_inflows_delete,
        name="exe_inflows_delete",
    ),
    path(
        "manage/collections/",
        views_ea.exe_collections,
        name="exe_collections",
    ),
    path(
        "manage/collections/<slug:collection_uuid>/edit/",
        views_ea.exe_collections_edit,
        name="exe_collections_edit",
    ),
    path(
        "manage/collections/<slug:collection_uuid>/delete/",
        views_ea.exe_collections_delete,
        name="exe_collections_delete",
    ),
    path(
        "manage/donations/",
        views_ea.exe_donations,
        name="exe_donations",
    ),
    path(
        "manage/donations/new/",
        views_ea.exe_donations_new,
        name="exe_donations_new",
    ),
    path(
        "manage/donations/<slug:donation_uuid>/edit/",
        views_ea.exe_donations_edit,
        name="exe_donations_edit",
    ),
    path(
        "manage/donations/<slug:donation_uuid>/delete/",
        views_ea.exe_donations_delete,
        name="exe_donations_delete",
    ),
    path(
        "manage/refunds/",
        views_ea.exe_refunds,
        name="exe_refunds",
    ),
    path(
        "manage/refunds/new/",
        views_ea.exe_refunds_new,
        name="exe_refunds_new",
    ),
    path(
        "manage/refunds/<slug:refund_uuid>/edit/",
        views_ea.exe_refunds_edit,
        name="exe_refunds_edit",
    ),
    path(
        "manage/refunds/<slug:refund_uuid>/delete/",
        views_ea.exe_refunds_delete,
        name="exe_refunds_delete",
    ),
    path(
        "manage/refunds/<slug:refund_uuid>/confirm/",
        views_ea.exe_refunds_confirm,
        name="exe_refunds_confirm",
    ),
    path(
        "manage/enrolment/",
        views_em.exe_enrolment,
        name="exe_enrolment",
    ),
    path(
        "manage/accounting/",
        views_ea.exe_accounting,
        name="exe_accounting",
    ),
    path(
        "manage/accounting/year",
        views_ea.exe_year_accounting,
        name="exe_year_accounting",
    ),
    path(
        "manage/accounting/run/<slug:run_uuid>/",
        views_ea.exe_run_accounting,
        name="exe_run_accounting",
    ),
    path(
        "manage/accounting/record/",
        views_ea.exe_accounting_rec,
        name="exe_accounting_rec",
    ),
    path(
        "manage/volunteer_registry/",
        views_em.exe_volunteer_registry,
        name="exe_volunteer_registry",
    ),
    path(
        "manage/volunteer_registry/new/",
        views_em.exe_volunteer_registry_new,
        name="exe_volunteer_registry_new",
    ),
    path(
        "manage/volunteer_registry/<slug:member_uuid>/edit/",
        views_em.exe_volunteer_registry_edit,
        name="exe_volunteer_registry_edit",
    ),
    path(
        "manage/users/volunteer_registry/<slug:member_uuid>/delete/",
        views_em.exe_volunteer_registry_delete,
        name="exe_volunteer_registry_delete",
    ),
    path(
        "manage/volunteer_registry/print",
        views_em.exe_volunteer_registry_print,
        name="exe_volunteer_registry_print",
    ),
    path(
        "manage/larpmanager/",
        views_eas.exe_larpmanager,
        name="exe_larpmanager",
    ),
    path(
        "feature/description/",
        views_eas.feature_description,
        name="feature_description",
    ),
    path(
        "manage/suggestions/<slug:perm>/",
        views_mg.exe_close_suggestion,
        name="exe_close_suggestion",
    ),
    path(
        "sticky-message/dismiss/<slug:message_uuid>/",
        views_mg.dismiss_sticky_message,
        name="dismiss_sticky_message",
    ),
    path(
        "manage/preferences/",
        views_eas.exe_preferences,
        name="exe_preferences",
    ),
    path(
        "manage/version/",
        views_eas.exe_version_upgrade,
        name="exe_version_upgrade",
    ),
    path(
        "manage/working_ticket/",
        views_ed.working_ticket,
        name="working_ticket",
    ),
    path(
        "manage/wwyltd/ajax/",
        views_mg.wwyltd_ajax,
        name="wwyltd_ajax",
    ),
    path(
        "manage/wwyltd/choices/",
        views_mg.wwyltd_choices_ajax,
        name="wwyltd_choices_ajax",
    ),
]
