# LarpManager - https://larpmanager.com
# Copyright (C) 2025 Scanagatta Mauro
#
# This file is part of LarpManager and is dual-licensed:
#
# 1. Under the terms of the GNU Affero General Public License (AGPL) version 3,
#    as published by the Free Software Foundation. You may use, modify, and
#    distribute this file under those terms.
#
# 2. Under a commercial license, allowing use in closed-source or proprietary
#    environments without the obligations of the AGPL.
#
# If you have obtained this file under the AGPL, and you make it available over
# a network, you must also make the complete source code available under the same license.
#
# For more information or to purchase a commercial license, contact:
# commercial@larpmanager.com
#
# SPDX-License-Identifier: AGPL-3.0-or-later OR Proprietary

from django.conf import settings as conf_settings
from django.contrib.auth import views as auth_views
from django.urls import include, path, re_path

from larpmanager.forms.member import (
    MyPasswordResetConfirmForm,
    MyPasswordResetForm,
    MyRegistrationFormUniqueEmail,
)
from larpmanager.views import auth as views_auth, base as views_base
from larpmanager.views.base import MyLoginView
from larpmanager.views.user import (
    accounting as views_ua,
    event as views_ue,
    member as views_um,
    miscellanea as views_ums,
    onetime as views_onetime,
    registration as views_ur,
)

urlpatterns = [
    path(
        "",
        views_base.home,
        name="home",
    ),
    path(
        "share/",
        views_ue.share,
        name="share",
    ),
    path(
        "legal_notice/",
        views_ue.legal_notice,
        name="legal_notice",
    ),
    path(
        "home/<slug:lang>/",
        views_base.home,
        name="home",
    ),
    path(
        "carousel/",
        views_ue.carousel,
        name="carousel",
    ),
    path(
        "calendar/past/",
        views_ue.calendar_past,
        name="calendar_past",
    ),
    path(
        "help/",
        views_ums.user_help,
        name="help",
    ),
    path(
        "help/attachment/<slug:attachment_uuid>/",
        views_ums.help_attachment,
        name="help_attachment",
    ),
    path(
        "language/",
        views_um.language,
        name="language",
    ),
    path(
        "profile/",
        views_um.profile,
        name="profile",
    ),
    path(
        "profile/upgrade/",
        views_um.profile_upgrade,
        name="profile_upgrade",
    ),
    path(
        "profile/upload/",
        views_um.profile_upload,
        name="profile_upload",
    ),
    path(
        "profile/rotate/<int:rotation_angle>/",
        views_um.profile_rotate,
        name="profile_rotate",
    ),
    path(
        "profile/privacy/",
        views_um.profile_privacy,
        name="profile_privacy",
    ),
    path(
        "profile/privacy/rewoke/<slug:slug>/",
        views_um.profile_privacy_rewoke,
        name="profile_privacy_rewoke",
    ),
    path(
        "security",
        views_um.security,
        name="security",
    ),
    path(
        "pre_register/",
        views_ur.pre_register,
        name="pre_register",
    ),
    path(
        "pre_register/<slug:event_slug>/remove",
        views_ur.pre_register_remove,
        name="pre_register_remove",
    ),
    path(
        "registrations/",
        views_um.registrations,
        name="registrations",
    ),
    path(
        "membership/",
        views_um.membership,
        name="membership",
    ),
    path(
        "membership/request/",
        views_um.membership_request,
        name="membership_request",
    ),
    path(
        "membership/request/test",
        views_um.membership_request_test,
        name="membership_request_test",
    ),
    path(
        "public/<slug:slug>/",
        views_um.public,
        name="public",
    ),
    path(
        "badges/",
        views_um.badges,
        name="badges",
    ),
    path(
        "leaderboard/",
        views_um.leaderboard,
        name="leaderboard",
    ),
    path(
        "leaderboard/<int:page>/",
        views_um.leaderboard,
        name="leaderboard",
    ),
    path(
        "badge/<slug:badge_uuid>/",
        views_um.badge,
        name="badge",
    ),
    path(
        "chats/",
        views_um.chats,
        name="messages",
    ),
    path(
        "chat/<slug:slug>/",
        views_um.chat,
        name="chat",
    ),
    path(
        "vote/",
        views_um.vote,
        name="vote",
    ),
    path(
        "unsubscribe/<str:token>/",
        views_um.unsubscribe,
        name="unsubscribe",
    ),
    path(
        "delegated/",
        views_um.delegated,
        name="delegated",
    ),
    path(
        "characters/",
        views_um.characters,
        name="characters",
    ),
    path(
        "accounting/",
        views_ua.accounting,
        name="accounting",
    ),
    path(
        "accounting/pay/<slug:event_slug>/",
        views_ua.accounting_payment,
        name="accounting_payment",
    ),
    path(
        "accounting/pay/<slug:event_slug>/<slug:method>/",
        views_ua.accounting_payment,
        name="accounting_payment",
    ),
    path(
        "accounting/registration/<slug:registration_uuid>/",
        views_ua.accounting_registration,
        name="accounting_registration",
    ),
    path(
        "accounting/registration/<slug:registration_uuid>/<slug:method>/",
        views_ua.accounting_registration,
        name="accounting_registration",
    ),
    path(
        "accounting/membership/",
        views_ua.accounting_membership,
        name="accounting_membership",
    ),
    path(
        "accounting/membership/<slug:method>/",
        views_ua.accounting_membership,
        name="accounting_membership",
    ),
    path(
        "accounting/donate/",
        views_ua.accounting_donate,
        name="accounting_donate",
    ),
    path(
        "accounting/refund/",
        views_ua.accounting_refund,
        name="accounting_refund",
    ),
    path(
        "accounting/cancelled/",
        views_ua.accounting_cancelled,
        name="accounting_cancelled",
    ),
    path(
        "accounting/payed/",
        views_ua.accounting_payed,
        name="accounting_payed",
    ),
    path(
        "accounting/payed/<slug:registration_uuid>/",
        views_ua.accounting_payed,
        name="accounting_payed",
    ),
    path(
        "accounting/wait/",
        views_ua.accounting_wait,
        name="accounting_wait",
    ),
    path(
        "accounting/webhook/satispay",
        views_ua.accounting_webhook_satispay,
        name="accounting_webhook_satispay",
    ),
    path(
        "accounting/webhook/stripe",
        views_ua.accounting_webhook_stripe,
        name="accounting_webhook_stripe",
    ),
    path(
        "accounting/stripe_confirm",
        views_ua.accounting_webhook_stripe,
        name="accounting_webhook_stripe",
    ),
    path(
        "accounting/webhook/sumup",
        views_ua.accounting_webhook_sumup,
        name="accounting_webhook_sumup",
    ),
    path(
        "accounting/webhook/redsys/",
        views_ua.accounting_webhook_redsys,
        name="accounting_webhook_redsys",
    ),
    path(
        "accounting/redsys/ko",
        views_ua.accounting_redsys_ko,
        name="accounting_redsys_ko",
    ),
    path(
        "accounting/credits/",
        views_ua.accounting_credits,
        name="accounting_credits",
    ),
    path(
        "accounting/tokens/",
        views_ua.accounting_tokens,
        name="accounting_tokens",
    ),
    path(
        "accounting/collection/",
        views_ua.accounting_collection,
        name="accounting_collection",
    ),
    path(
        "accounting/collection/<slug:collection_code>/",
        views_ua.accounting_collection_manage,
        name="accounting_collection_manage",
    ),
    path(
        "accounting/collection/<slug:collection_code>/participate/",
        views_ua.accounting_collection_participate,
        name="accounting_collection_participate",
    ),
    path(
        "accounting/collection/<slug:collection_code>/close/",
        views_ua.accounting_collection_close,
        name="accounting_collection_close",
    ),
    path(
        "accounting/collection/<slug:collection_code>/redeem/",
        views_ua.accounting_collection_redeem,
        name="accounting_collection_redeem",
    ),
    path(
        "accounting/submit/<slug:payment_method>/<slug:invoice_uuid>/<path:redirect_path>/",
        views_ua.accounting_submit,
        name="accounting_submit",
    ),
    path(
        "accounting/confirm/<slug:invoice_cod>/",
        views_ua.accounting_confirm,
        name="accounting_confirm",
    ),
    path(
        "shuttle/",
        views_ums.shuttle,
        name="shuttle",
    ),
    path(
        "shuttle/new/",
        views_ums.shuttle_new,
        name="shuttle_new",
    ),
    path(
        "shuttle/edit/<slug:shuttle_uuid>/",
        views_ums.shuttle_edit,
        name="shuttle_edit",
    ),
    re_path(
        r"^paypal/",
        include("paypal.standard.ipn.urls"),
    ),
    path(
        "register/conditions/",
        views_ur.register_conditions,
        name="register_conditions",
    ),
    path(
        "at/<slug:url_cod>/",
        views_ums.url_short,
        name="url_short",
    ),
    path(
        "util/<slug:util_cod>/",
        views_ums.util,
        name="util",
    ),
    path(
        "register/",
        views_auth.MyRegistrationView.as_view(
            form_class=MyRegistrationFormUniqueEmail,
            success_url="/",
        ),
        name="registration_register",
    ),
    path("login/", MyLoginView.as_view(), name="login"),
    path("login/otp/", views_um.otp_verify, name="otp_verify"),
    path(
        "logout/",
        auth_views.LogoutView.as_view(next_page=conf_settings.LOGOUT_REDIRECT_URL),
        name="logout",
    ),
    path(
        "password_reset/",
        views_auth.MyPasswordResetView.as_view(form_class=MyPasswordResetForm),
        name="password_reset",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views_auth.MyPasswordResetConfirmView.as_view(form_class=MyPasswordResetConfirmForm),
        name="password_reset_confirm",
    ),
    path(
        "after_login/<slug:subdomain>/",
        views_base.after_login,
        name="after_login",
    ),
    path(
        "after_login/<slug:subdomain>/<path:path>/",
        views_base.after_login,
        name="after_login",
    ),
    path(
        "tutorial_query/",
        views_base.tutorial_query,
        name="tutorial_query",
    ),
    path(
        "set_member_config/",
        views_base.set_member_config,
        name="set_member_config",
    ),
    path("upload_media/", views_base.upload_media, name="upload_media"),
    path(
        "watch/<str:token>/",
        views_onetime.onetime_access,
        name="onetime_access",
    ),
    path(
        "stream/<str:token>/",
        views_onetime.onetime_stream,
        name="onetime_stream",
    ),
    path(
        "integration/redirect/",
        views_ums.app_integration_redirect,
        name="app_integration_redirect",
    ),
    path(
        "invite/role/<str:token>/",
        views_ums.role_invite_redeem,
        name="role_invite_redeem",
    ),
    path(
        "api/json/",
        views_ue.api_json,
        name="api_json",
    ),
    path(
        "api/json/<slug:lang>/",
        views_ue.api_json,
        name="api_json",
    ),
]
